### ISSUE TITLE
allow expressions to be ended by end of file?

### ISSUE THREAD

**Issue by oxinabox** [google-research/dex-lang#106]
If one has a file that does not end with a new line then this is an error.

Example:
```
:p (1. + 2.) * 3.
Parse error:1:18:
  |
1 | :p (1. + 2.) * 3.
  |                  ^
unexpected end of input
expecting "--o", "->", "..", "..<", "<..", "<..<", "=>", '$', '-', '.', backquoted name, end of line, expression, or infix operator
```

The error message tells the truth, it was not expecting an end of input  there, and putting in a end of line makes the code work,
but it is a otherwise complete expression.

**Comment by dougalm** [comment]
Yes, this often bites me too. I'll fix it.
