### ISSUE TITLE
Implement loop invariant code motion

### ISSUE THREAD

**Issue by axch** [google-research/dex-lang#1069]
@duvenaud, presumably among others, wishes this would be fast:
```
for i. divide xs.i (sum xs)
```
To make that fast, we have to lift the loop-invariant and relatively expensive `sum xs` out of the `for`.

**Comment by apaszke** [comment]
I'm actually working on a pass that has a very similar flavor (hoisting and deduplicating Ix dicts), so it shouldn't be too difficult to adapt the same code to do LICM too.

**Comment by apaszke** [comment]
We actually have this optimization now (implemented in #1099)!
