### ISSUE TITLE
include seems not to be bringing things into scope

### ISSUE THREAD

**Issue by oxinabox** [google-research/dex-lang#107]
I was working on another example and I wanted to use the [PSO `optimize`](https://github.com/google-research/dex-lang/blob/5298ef13ceae429830e75b18512fe285e8059800/examples/particle-swarm-optimizer.dx#L59) function.
So I did:

```
include "examples/particle-swarm-optimizer.dx"
```

and that caused a bunch of text to show-up in my output (i think all the `:p` print statements).
so I figured it was working

but when I tried to call `optimize` 
I got: `Error: variable not in scope: optimize`

cf https://github.com/google-research/dex-lang/issues/40

**Comment by dougalm** [comment]
I'm excited that you're working on another example! Sorry for the breakage. I should warn that things are even more unstable than usual right now. We just merged a major change, #101, but we're still not quite at the point where everything is working again. Notice that the [include tests are commented out](https://github.com/google-research/dex-lang/blob/main/makefile#L48).

**Comment by oxinabox** [comment]
yeah, i noticed that.
Figured I would open an issue about this particular point, so it can be closed once that is fixed
