### ISSUE TITLE
Support incomplete explicit type binders

### ISSUE THREAD

**Issue by duvenaud** [google-research/dex-lang#1077]
This is a known issue, but I just want to leave this concrete use case here:

```
interface Subset a_sub a
  inject'           : a_sub -> a
  can_project a_sub : a -> Bool
  unsafe_project'   : a -> a_sub

Not implemented:
Please report this at github.com/google-research/dex-lang/issues

Permuted or incomplete explicit type binders are not supported yet.
```

**Comment by duvenaud** [comment]
I figured out how to get this to work, it was right there in the error message.  I just had to include all the binders, including one superfluous one, like so:
```
can_project a_sub a : a -> Bool
```

Since now this seems to me like an unimportant and rarely-used feature, I will close this for now.

**Comment by apaszke** [comment]
Well it is a legit TODO, so we can keep it open :)
