### ISSUE TITLE
Can't build FFI on Apple M1

### ISSUE THREAD

**Issue by jakesnell** [google-research/dex-lang#1107]
I can build dex fine on my M1 MacBook Pro, but `build-ffis` doesn't work. Possibly related to this issue? https://github.com/haskell/cabal/issues/8227

```
$ make build-ffis
stack --stack-yaml=stack-macos.yaml build --ghc-options="-j +RTS -A256m -n2m -RTS" --work-dir .stack-work-ffis --force-dirty --flag dex:foreign --flag dex:optimized
Building all executables for `dex' once. After a successful build of all of them, only specified executables will be rebuilt.
dex> configure (lib + exe)
Configuring dex-0.1.0.0...
Cabal-simple_mPHDZzAJ_3.2.1.0_ghc-8.10.7: Cannot build some foreign libraries:
Building foreign libraries is currently only supported on OSX, Linux and
Windows
```

**Comment by apaszke** [comment]
Yeah I think it's just a Cabal limitation that we can't do much about.

You could try bumping the resolver in `stack-macos.yaml` to `nightly-2022-10-06` and adding `Cabal-3.8.1.0` to `extra-packages` to override the default (3.6, but the fix is only in 3.8).
