### ISSUE TITLE
"Compiler bug" message when printing a lambda

### ISSUE THREAD

**Issue by hexahedria** [google-research/dex-lang#114]
```
>=> :p \x. x + 1.0
Compiler bug!
Please report this at github.com/google-research/dex-lang/issues

src/lib/TopLevel.hs:177:20-59: Non-exhaustive patterns in lambda
```
Admittedly, printing a lambda is a weird thing to do. But it seems like there could be a better error message here, and it seems like it's failing even before getting to the pretty printer.

**Comment by dougalm** [comment]
Fixed by #133.
