### ISSUE TITLE
Actually add `var` syntax for even more convenient access to the state effect

### ISSUE THREAD

**Issue by axch** [google-research/dex-lang#1148]
As of PR #1147, using the State effect stops being the cumbersome
```
with_state initialize \x.
  ...
```
and instead becomes the relatively convenient
```
x <- with_state initialize
...
```
notably without increasing the indentation level.

Do we feel that state is important enough to special-case further, down to
```
var x = initialize
...
```
or
```
var x <- initialize
...
```
?

Note that if we just rename `with_state` to `var` we can already have
```
x <- var initialize
...
```

**Comment by dougalm** [comment]
I don't see a need for `Var` anymore. The ergonomic improvement on top of `<-` seems small. Let's close this issue since it's subsumed by #1147.
