### ISSUE TITLE
Add a `Data` constraint

### ISSUE THREAD

**Issue by dougalm** [google-research/dex-lang#1150]
This came up again recently when we added the role system (#1138). We currently don't check that parameters with the `DataParam` are in fact representable data.

As with `Ix`, the constraint will need to appear in some type constructors. For example, `data RangeFrom q:Type i:q = ...` should really be `data RangeFrom q:Type [Data q] i:q`, so that the type of `i` can be verified to satisfy the `Data` constraint and its role can be `DataParam`.

The type constructor `Ref` should probably have the constraint too (i.e. `Ref : (a:Type) -> [Data a] -> Type`), a bit like `=>` having an `Ix` constraint. That will solve issues like #694. And we can do the same autoquantification thing we do with `Ix` to make the syntax lighter.

What should we call this constraint? Our working name has been `Data` but that word is *super* overloaded, and I always find myself forced to use scare quotes when I talk about it. (The title of this issue couldn't have been just "Add a data constraint".) `PlainData`? `PlainOldData`? `RepresentableData`?

**Comment by duvenaud** [comment]
I dislike the current use of `data` in both Dex and in Haskell to define a new type.  Especially because data are in a sense the opposite of types.  I realize that we don't want to spend weirdness points, but that could reduce the overloadedness of `Data`.

**Comment by axch** [comment]
#609 is an example of a specific use-case for this (better error when trying to hold a function in a State-effect reference).

**Comment by axch** [comment]
We might also be able to provide a better error message for tables of functions #177 until we implement the closure-conversion.

**Comment by axch** [comment]
I think my opinion on the name will depend on how often it appears explicitly, and how many use-cases it covers.  For instance, Haskell has at least four classes that read to me like "This is normal data, nothing weird":

- `Typeable a`, which (ironically) supports dynamic typing 
- `Typeable a => Data a`, which provides the "one-layer traversal" method needed to implement Scrap Your Boilerplate
- `Generic a`, which provides methods needed for generic programming (an alternative to Scrap Your Boilerplate?)
- `Storable a`, which provides methods to write values to raw memory (e.g., the size of a value in bytes)

Do we have a clear sense of how `Data` in Dex compares in function to these classes?  (Also, does Haskell have any others that matter for this purpose?)
