### ISSUE TITLE
Spurious 'Leaked local variables' error.

### ISSUE THREAD

**Issue by duvenaud** [google-research/dex-lang#1176]
Now that constraints can be interleaved with arguments in type constructors, I thought I'd revisit some TODOs in `set.dx`.  However,

```
data SetIx a [Ord a] set:(Set a) =
  MkSetIx Nat

instance Eq (SetIx a set) given {a set} [Ord a]
  (==) = \ix1 ix2. ordinal ix1 == ordinal ix2
```
gives the error: `Leaked local variables:[a]`

I think that's a nice minimal working example.

If you want another, more complicated, example, I think this bug actually hit me twice in one night:  I switched to `set.dx` because I hit a similar error in what I was actually working on:
```
def PartialsUpToOrder (dims:Type) [Ix dims] (order:Nat) : Type =
  dims=>(Post (Fin order))

data AllPartialsUpTo dims:Type [Ix dims] order:Nat partial:(PartialsUpToOrder dims order) =
  MkAllPartialsUpTo i:(PartialsUpToOrder dims order)

instance Ord Bool
  (<) = \x y. (b_to_n x) < (b_to_n y)
  (>) = \x y. (b_to_n x) > (b_to_n y)

instance Ix (AllPartialsUpTo dims order partial) given {dims order partial} [Ix dims]
  size = sum for i. ordinal partial.i
  -- Need that get_changed_dim i == get_changed_dim (reflect i)
  ordinal = \(MkAllPartialsUpTo p).
    cur_bin = from_just $ search_sorted (for d. p.d < partial.d) True
    first_bins_count = sum for i:(..cur_bin). ordinal partial.(inject _ i)
    cur_bin_count = ordinal p.cur_bin
    first_bins_count + cur_bin_count
  unsafe_from_ordinal = \o.
    cs = cumsum for i. ordinal partial.i
    cur_bin = from_just $ search_sorted cs o
    ans = for i. case i < cur_bin of
      True  -> partial.i
      False -> case i == cur_bin of
        True -> from_ordinal _ $ unsafe_nat_diff o cs.i
        False -> 0
    MkAllPartialsUpTo ans
```
gives
```
Leaked local variables:[order]

instance Ix (AllPartialsUpTo dims order partial) given {dims order partial} [Ix dims]
                                                        ^^^^^
```

**Comment by duvenaud** [comment]
Hmmm, it sounds like you're saying that the compiler is correct in saying that `a` is leaked?  I guess I don't understand why `a` is leaked instead of just being an argument that the function is polymorphic in, just like `set`.

**Comment by duvenaud** [comment]
Wow, I didn't even realize that I could type implicit variables with the new `{}` syntax, but it makes perfect sense.  Thanks for finding a fix!  And yes, I like your suggested naming scheme.

**Comment by axch** [comment]
Since the error message is better now, I'm going to close this as "fixed enough".  Arguably, Dex ought to be able to infer that `set` should have type `Set a` without leaking the `a`, but getting that right is not a high priority right now.
