### ISSUE TITLE
Compiler bug: Algebraic simplification failed to model index computations

### ISSUE THREAD

**Issue by emilyfertig** [google-research/dex-lang#1178]
I ran into this when working on an expanded Gaussian process regression example in `kernelregression.dx` (code/error message below).

[Dex Output GPRM compiler bug.pdf](https://github.com/google-research/dex-lang/files/10197997/Dex.Output.GPRM.compiler.bug.pdf)
[kernelregression.txt](https://github.com/google-research/dex-lang/files/10198003/kernelregression.txt)

**Comment by axch** [comment]
The rewrite #1209 eliminated the compilation error, so I will close this.

We now get a mean and covariance, though unfortunately the covariance ends up full of NaNs, suggesting a numerical problem somewhere (possibly in the standard library).  But that's a separate issue.
