### ISSUE TITLE
Homebrew Include Directory Incorrectly Specified for M2 in Makefile

### ISSUE THREAD

**Issue by chrisp1934** [google-research/dex-lang#1184]
I am running macOS Monterey 12.6 with an M2 processor. I am using Homebrew 3.6.15 and I install libpng 1.6.39. When attempting to install Dex based on the instructions given in the README, I was getting the following error:

```
clang++ -fPIC -std=c++11 -fno-exceptions -fno-rtti -pthread -DDEX_LIVE -c -emit-llvm src/lib/dexrt.cpp -o src/lib/dexrt.bc
src/lib/dexrt.cpp:30:10: fatal error: 'png.h' file not found
#include <png.h>
         ^~~~~~~
1 error generated.
make: *** [src/lib/dexrt.bc] Error 1
```

The current Makefile specifies an include directory supported by Intel Macs. I changed the Makefile to specify the new include directory `/opt/homebrew/include`. It seems to be working so far. The code I have for lines 97-100 is below:

```
# libpng
ifneq (,$(wildcard /opt/homebrew/include/png.h))
CFLAGS := $(CFLAGS) -I/opt/homebrew/include
endif
```

Can this be fixed to support all machines?

**Comment by axch** [comment]
Thanks for your interest!  We're not worrying super-actively about OS support right now, but if you want to throw us a PR that seems reasonable to you, if it passes tests we'll merge it!

**Comment by chrisp1934** [comment]
Will do. Thanks!
