### ISSUE TITLE
Can't count function arguments

### ISSUE THREAD

**Issue by axch** [google-research/dex-lang#1265]
```
rand_vec(5, internal_cast, a=Float32)
> Type error:Wrong number of arugments provided. Expected 3 but got 2
>
> rand_vec(5, internal_cast, a=Float32)
> ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
```

But I clearly passed three arguments!  The actual complaint is about a missing third *explicit* (i.e., positional) argument; this error message is terrible.

**Comment by dougalm** [comment]
would it be enough to just change the message to "wrong number of positional arugments provided"? We could even spell it as "arguments" which is more traditional.
