### ISSUE TITLE
Dictionary inference not working for Eq

### ISSUE THREAD

**Issue by duvenaud** [google-research/dex-lang#142]
```
def is_equal (dict: Eq a) ?-> (v1:a) -> (v2:a) : Bool =
  v1 == v2
```

Gives

```Type error:Couldn't synthesize a class dictionary for: Eq dict```

**Comment by dougalm** [comment]
Bad error message! The problem is that we only synthesize dictionaries from arguments that are bound with the `?=>` arrow. It works if you replace `?->` with `?=>`.

**Comment by duvenaud** [comment]
D'oh!  I knew that.
