### ISSUE TITLE
Entering multi-line expressions in REPL

### ISSUE THREAD

**Issue by oxinabox** [google-research/dex-lang#15]
I thought I would copy-paste some of the examples in the tutorial into the REPL.
All the multiline ones seem to fail.
I moved them into a script and run the script and that works.

e.g.:
```
:p x = 1.                -- let binding
   y = (z = 2.; z + 1.)  -- let binding of a nested let expression
   ..                    -- escaped cosmetic line break
   x + y                 -- body of let expression
```

Results in:
```
>=> :p x = 1.                -- let binding
Parse error:2:1:
  |
2 | <empty line>
  | ^
unexpected end of input
expecting decl or expr

>=>    y = (z = 2.; z + 1.)  -- let binding of a nested let expression
Parse error:1:4:
  |
1 |    y = (z = 2.; z + 1.)  -- let binding of a nested let expression
  |    ^^
unexpected "y "
expecting ".." or end of line

>=>    ..                    -- escaped cosmetic line break
Parse error:2:1:
  |
2 | <empty line>
  | ^
unexpected end of input
expecting end of line

>=>    x + y                 -- body of let expression
Parse error:1:4:
  |
1 |    x + y                 -- body of let expression
  |    ^^
unexpected "x "
expecting ".." or end of line
```

Either I am doing something wrong,
or the REPL needs to try parsing when <kbd>Enter</kbd> is pressed
and if that fails du to `unexpected end of input`, it needs to continue to allow input.

**Comment by dougalm** [comment]
Thanks for catching and reporting this. It used to work but I broke it by adding different kind of parser error recovery, which was firing first. I'll push the fix and a test so it doesn't break again. Unfortunately you still can't copy-and-paste `'`-prefixed multiline prose blocks or `>`-prefixed output block.
