### ISSUE TITLE
Segfaults on Mac

### ISSUE THREAD

**Issue by duvenaud** [google-research/dex-lang#154]
Since I synced on Thursday evening, about half the tests fail with segfault, as does the web interface.  I also built a fresh pull of the current repo from scratch today but it has the same errors.  Here's the output of ```make tests```:

```
% make tests
rm -rf test-scratch/
mkdir -p test-scratch/
python3 misc/py/generate-dex-data.py
stack build
misc/check-quine examples/uexpr-tests.dx stack exec         dex -- script --allow-errors
OK
misc/check-quine examples/type-tests.dx stack exec         dex -- script --allow-errors
OK
misc/check-quine examples/eval-tests.dx stack exec         dex -- script --allow-errors
misc/check-quine: line 11: 53538 Segmentation fault: 11  ${@:2} $1 > $tmpout 2> $errout
misc/check-quine examples/shadow-tests.dx stack exec         dex -- script --allow-errors
OK
misc/check-quine examples/monad-tests.dx stack exec         dex -- script --allow-errors
OK
misc/check-quine examples/ad-tests.dx stack exec         dex -- script --allow-errors
OK
misc/check-quine examples/mandelbrot.dx stack exec         dex -- script --allow-errors
OK
misc/check-quine examples/pi.dx stack exec         dex -- script --allow-errors
OK
misc/check-quine examples/sierpinsky.dx stack exec         dex -- script --allow-errors
misc/check-quine: line 11: 53601 Segmentation fault: 11  ${@:2} $1 > $tmpout 2> $errout
misc/check-quine examples/regression.dx stack exec         dex -- script --allow-errors
misc/check-quine: line 11: 53609 Segmentation fault: 11  ${@:2} $1 > $tmpout 2> $errout
misc/check-quine examples/brownian_motion.dx stack exec         dex -- script --allow-errors
misc/check-quine: line 11: 53617 Segmentation fault: 11  ${@:2} $1 > $tmpout 2> $errout
misc/check-quine examples/particle-swarm-optimizer.dx stack exec         dex -- script --allow-errors
misc/check-quine: line 11: 53625 Segmentation fault: 11  ${@:2} $1 > $tmpout 2> $errout
misc/check-quine examples/ode-integrator.dx stack exec         dex -- script --allow-errors
misc/check-quine: line 11: 53633 Segmentation fault: 11  ${@:2} $1 > $tmpout 2> $errout
misc/check-quine examples/parser-tests.dx stack exec         dex -- script --allow-errors
OK
misc/check-quine examples/serialize-tests.dx stack exec         dex -- script --allow-errors
OK
misc/check-quine examples/tiled-matmul.dx stack exec         dex -- script --allow-errors
OK
misc/check-quine examples/mcmc.dx stack exec         dex -- script --allow-errors
misc/check-quine: line 11: 53674 Segmentation fault: 11  ${@:2} $1 > $tmpout 2> $errout
misc/check-no-diff \
	  examples/repl-multiline-test-expected-output \
	  <(stack exec         dex -- repl < examples/repl-multiline-test.dx)
OK
```

The latest commit that I had pulled when I first saw these errors on Thursday was the [AD merge](https://github.com/google-research/dex-lang/commit/3744952691a04570911d96ebe83a0ee1a2cc6f0d) but since it's a segfault error maybe it was one of the earlier ones that day, perhaps [the malloc_dex one](https://github.com/google-research/dex-lang/commit/24e0639a526e8e61302b46618ae36115f55d6c16) or the [OrcJIT one](https://github.com/google-research/dex-lang/commit/ca32d8d471d748c98de0b79cdd96baeab50c4a65).  Just guessing.

The only change I made to the repo before building is the one I always make, which is adding 
```
+
+flags:
+  llvm-hs:
+    shared-llvm: false
```
to ```stack.yaml```.

**Comment by apaszke** [comment]
Whoops, it might be the JIT change, because it has uncovered some segfault-causing errors in the previous implementation on Linux. There might be something I've missed. Will start digging tomorrow!

**Comment by apaszke** [comment]
Can reproduce segfaults on exactly the same tests on my mac, so at least there's that.

**Comment by duvenaud** [comment]
Reverting back to [the commit before the JIT change](https://github.com/google-research/dex-lang/commit/c70ff65ff6253ad4df1665d425a78f85203a9b69) gets rid of the segfault, so I think it's one of the commits between that and the AD merge.

**Comment by apaszke** [comment]
Uh this was a weird one, but #159 should fix it.

**Comment by duvenaud** [comment]
Yes, all tests now pass.  Thanks for the quick turnaround!
