### ISSUE TITLE
Concrete syntax for dependent table literals

### ISSUE THREAD

**Issue by duvenaud** [google-research/dex-lang#168]
I'm porting the Dopri 5 ODE solver to Dex, and I wanted to show off its ragged array handling.  However, it looks like Dex expects every row to have the same length:

```
beta = [[1.0],
       [3.0, 9.0],
       [44.0, -56.0, 32.0]]
Type error:
Expected: ((Fin 1) => Real)
  Actual: ((Fin 2) => Real)

       [3.0, 9.0],
```

Edit:

It looks like the bottleneck is concatenating the jagged arrays together, not parsing them:

```
beta1 = [1.0 / 5.0]
beta2 = [3.0 / 40.0, 9.0 / 40.0]
beta3 = [44.0 / 45.0, -56.0 / 15.0, 32.0 / 9.0]
beta = [beta1, beta2, beta3]
Type error:
Expected: ((Fin 1) => Real)
  Actual: ((Fin 2) => Real)

beta = [beta1, beta2, beta3]
```

**Comment by dougalm** [comment]
I like to tout Dex's ragged array handling but it doesn't exist the actual world yet. That should change soon (the ADT branch was a first step). But it won't be as simple as `[[1], [2,3]]` (what would the type of that be?). It'll look more like this:

```
data List a =
  MkList : (n:Int) ?-> (n=>a) -> List a

xs : (Fin 2 => List Int) = [MkList [1], MkList [1,2]]

```

**Comment by duvenaud** [comment]
Hmmm, maybe you need a harder example, because Dex can already construct and type something like ```[[1.0], [2.0,3.0]]```:

```
>=> :p for i:(Fin 2). for j:(..i). (i2r (1 + (ordinal j) + (ordinal i)))
[[1.0]@(..(0@Fin 2)), [2.0, 3.0]@(..(1@Fin 2))]
>=> :t for i:(Fin 2). for j:(..i). (i2r (1 + (ordinal j) + (ordinal i)))
((i:(Fin 2)) => (..i) => Real)
```

But I think I see your point, it wouldn't work if there wasn't a nice pattern to the lengths.  In my case I want a lower-diagonal matrix, so I think the existing type system can handle it.  But that's not what my github issue asked for!

**Comment by dougalm** [comment]
Ah, I missed that you were interested in structured dependent tables (like triangular matrices) rather than arbitrary raggedness. Yes, we don't have concrete syntax for dependent table literals. It's a bit tricky. We'll need to bring an index in scope somehow. I'll think about it.

**Comment by duvenaud** [comment]
Thanks - I didn't quite realize what I was asking for when I opened this issue.  But yes, all I want in this instance is to be able to create a diagonal matrix, which should be handleable in the current type system, but not in the syntax.
