### ISSUE TITLE
Pattern matching for table literals

### ISSUE THREAD

**Issue by dougalm** [google-research/dex-lang#172]
It's a natural thing to want now that we have pattern matching on data constructors. Should just be another case for `UPat` and corresponding parser/inference rules.

```
vec = [1, 2, 3]
[x, y, z] = vec
```

**Comment by gilbo** [comment]
Just checking, is this still open?  I may try to knock this one out.

**Comment by dougalm** [comment]
It's still open! Let me know if I can help.

**Comment by dougalm** [comment]
Fixed by #281.
