### ISSUE TITLE
Allow some control over numerical precision

### ISSUE THREAD

**Issue by dougalm** [google-research/dex-lang#182]
Let's add base types like `Float64`, `Float32`, `Int64`, `Int32` and make `Int` and `Real` aliases for these, possibly controlled by a command-line flag. Allowing 32-bit precision will be very important for good performance on accelerators.

Separately, we should probably just call it `Float` instead of `Real`. Who are we kidding?

**Comment by jekbradbury** [comment]
It's probably not in scope right now, but it would be pretty cool if Dex could become a testbed for more explicit thinking about numerics, in addition to all the other things it does! Having something like a typeclass hierarchy for floating point representations, exposing the ways in which they follow and diverge from familiar algebraic structures, the differences between formats with and without subnormals, and enabling the various novel low-precision types implemented on ML chips, etc. would help with research and clarity in that world.
