### ISSUE TITLE
A typeclass for index sets

### ISSUE THREAD

**Issue by dougalm** [google-research/dex-lang#186]
Programs like this are an embarrassingly common source of hard compiler crashes:

```
>=> ordinal 1
dex: Unexpected type Int
CallStack (from HasCallStack):
  error, called at src/lib/Embed.hs:763:8 in dex-0.1.0.0-E6hv5RWTwEZBvnlq4z9NtQ:Embed
```

The problem is that `ordinal` has type `a -> Int`, but it should really be `Ix a ?=> a -> Int`, where `Ix a` is a typeclass constraint indicating that `a` is isomorphic to `Fin n` for some `n`. The index set typeclass might look something like this:

```
class Ix a where
  size : Int
  toFin   : a -> Fin size
  fromFin : Fin size -> a
```

It's a bit tricky because it's a dependent dictionary (the value of `size` is used in the types of `toFin` and `fromFin`).

We'd need to use this constraint a lot. For example, matmul would need it three times:
```
matmul : Ix l ?=> Ix m ?=> Ix n ?=> (l=>m=>Real) -> (m=>n=>Real) -> (l=>n=>Real)
```
I hope we can find a way to avoid all that boilerplate. It's obvious from the rest of the type that `l`, `m` and `n` have to be index sets since they're appear on the left-hand side of table arrows.

Maybe we can make `IndexSet` a subtype of `Type` instead of using a typeclass? Or maybe we can infer the constraints automatically? At the very least, we can aim for lighter syntax.

Separately, we should see if we can allow user-defined index sets. It'll simplify the internals a lot if we can make "index set" purely a userspace concept and just work with `Fin n` internally.

**Comment by hexahedria** [comment]
One note about this: if we want to allow records (and maybe variants) as index sets, and we define index sets as typeclasses, we would need to be able to dynamically synthesize the `Ix` typeclass, since we can't write out all possible record types in the prelude.

**Comment by dougalm** [comment]
Good point. We probably want to do that for records for some other typeclasses too (like `Eq`).

**Comment by hexahedria** [comment]
Perhaps the orderedness of index sets could also be defined based on typeclasses? We could have expectations ("laws") that if a dataclass is both `Ix` and `Ord`, then its iteration order matches its comparison order. Then we could require that a dataclass be both `Ix` and `Ord` if you want to use `ordinal` or `fromOrdinal` (at least in userspace). A type that is `Ix` but not `Ord` would be assumed to be stored in an arbitrary order that user code shouldn't depend on; this would allow us to avoid exposing implementation details about what order we iterate over records/variants, for instance.

Extension of this: when serializing an array with an index set that is `Ix` and `Ord`, we could print it as we do now, but when serializing one that is just `Ix`, we could render it in key-value notation. (If we wanted to avoid introducing new notation we could even pretty-print the table as a case statement:
```
:p myTable
> for i. case i of
      {a = 0 @ Fin 4, b = 0 @ Fin 3} -> 3.
      {a = 0 @ Fin 4, b = 1 @ Fin 3} -> 3.
      ...
```
)

**Comment by dougalm** [comment]
Added in #732!
