### ISSUE TITLE
Guide on new backend

### ISSUE THREAD

**Issue by zjin-lcf** [google-research/dex-lang#190]
May you please suggest specifically how people can add a new backend (e.g. OpenCL) ?

Thanks

**Comment by apaszke** [comment]
Hmmm, can LLVM target OpenCL or would you like to use something else for code generation?

**Comment by zjin-lcf** [comment]
Without knowledge of Haskell, it is difficult to know how to add a backend because your code generation is written with Haskell. Is that right ?

**Comment by apaszke** [comment]
Yes, we use Haskell to develop the compiler, although the actual low-level code generation is usually taken care of by a lower-level library written in another language such as LLVM. But there is no way to add a new backend without modifying the Haskell code.

**Comment by zjin-lcf** [comment]
Okay. Thanks.
