### ISSUE TITLE
Is array printing broken?

### ISSUE THREAD

**Issue by oxinabox** [google-research/dex-lang#20]
This could be me having a bad LLVM build some how.

But it seems lilke I can't `:p` an array.

```
~/dex-lang(git✱≠master)❱ ✘ ❱ stack --  exec dex repl
>=> c = [1, 2, 3]

>=> :p c
Assertion failed: ((i >= FTy->getNumParams() || FTy->getParamType(i) == Args[i]->getType()) && "Calling a function with a bad signature!"), function init, file /Users/oxinabox/progmisc2/llvm/llvm-8.0.0.src/lib/IR/Instructions.cpp, line 379.
fish: 'stack --  exec dex repl' terminated by signal SIGABRT (Abort)
```

There are examples of this working in the tuitorial.

**Comment by dougalm** [comment]
Hmm, I've never seen anything like that. I can't reproduce. The tests have plenty of array prints in them. I assume they break too?

**Comment by oxinabox** [comment]
It seems my tests are ... very broken.

I have LLVM rebuilding.
Lets see after that is  complete.
It might have gotten annoyed at me moving some things around.

**Comment by oxinabox** [comment]
It is still very broken.

One hopeful clue is that
` file /Users/oxinabox/progmisc2/llvm/llvm-8.0.0.src/lib/IR/Instructions.cpp, line 379.`

is still showing up.
It that was from several builds ago; and has been deleted.

So somewhere some cache is getting hit.
I already did `stack clean` and `rm -r ~/.stack/snapshots`

**Comment by oxinabox** [comment]
Still not sure why my error message is pointing to a very old file.
Can't find any references to it in the binaries.

It is interesting to note that this error is from here
 https://github.com/llvm/llvm-project/blob/d2298e74235598f15594fe2c99bbac870a507c59/llvm/lib/IR/Instructions.cpp#L371-L380

Which is hidden behind a `#ifndef NDEBUG`
so it might well be that since I have a source build of LLVM built without the `NDEBUG` being set.
I might be seeing this.
Where as perhasp the distributed versions may set it, and thus not have this extra check.
If this is the cause then I guess it means something a bit funky is being done by dex or llvm-hs somewhere.

Builting LLVM for the nth time today now.

**Comment by oxinabox** [comment]
Here we go, some progress
After deleting `~/.stack` entirely, I think I am now hitting the right instakll of LLVM with that check commented out,.
And I get a new error

```
>=> c = [1., 2.]

>=> c
Call parameter type does not match function signature!
double* inttoptr (i64 140648466352256 to double*)
 i8*  tail call void @memcpy_dex(double* inttoptr (i64 140648466352256 to double*), double* inttoptr (i64 140648485250112 to double*), i64 16)
in function thefun
LLVM ERROR: Broken function found, compilation aborted!
```

**Comment by dougalm** [comment]
That's progress! And it's extremely plausible that I'm doing something broken on the Dex side and my version of LLVM is letting me get away with it.

`thefun` is actually what [Dex creatively calls the main (and only) function it compiles each time](https://github.com/google-research/dex-lang/blob/master/src/lib/JIT.hs#L464).


I'll be afk for a few hours but I'll take a look later when I get back.

**Comment by oxinabox** [comment]
> thefun is actually what Dex creatively calls the main (and only) function it compiles each time.

ah yes, I was misreading `ag`'s output.

---

This error is from the Verifier.

https://github.com/llvm/llvm-project/blob/d2298e74235598f15594fe2c99bbac870a507c59/llvm/lib/IR/Verifier.cpp#L2775

I think the next things to do is to:
 - Lookup how debian or brew builds LLVM, and match their settings
 - actually  `#define NDEBUG` fully (rather than comment out one section)
 - try a source build of LLVM in linux (I think my instructions should more or less work the same except the mac special can just be skipped i guess)

But it will have to be another day.
Its been a fun day of it today.

**Comment by dougalm** [comment]
Yes, it looks like I'm being sloppy with pointer types, treating `double*` as `i8*`. Printing out the LLVM gives a bit more context. (I assume your version crashes before it prints anything?)

    >=> c = [1.0, 2.0, 3.0]
    >=> :llvm c

    ...

    ; ModuleID = 'test'
    source_filename = "<string>"

    define void @thefun() local_unnamed_addr {
    start_block:
      tail call void @memcpy_dex(double* inttoptr (i64 65460064 to double*), double* inttoptr (i64 64562912 to double*), i64 24)
      ret void
    }

    declare void @memcpy_dex(i8*, i8*, i64) local_unnamed_addr

It's weird that my LLVM version doesn't seem to mind. I'll investigate whether there are more validation checks I can turn on.

**Comment by dougalm** [comment]
It turns out I hadn't been invoking LLVM's verifier. llvm-hs [exposes it nicely here](http://hackage.haskell.org/package/llvm-hs-9.0.1/docs/LLVM-Analysis.html). I just added it to the LLVM printer (70c492b). Adding it before every compilation exposes plenty of errors, unsurprisingly!

Running the verifier on your example, I get exactly the same error you're seeing. That solves the mystery. Your version must have those asserts turned on and so it was hitting them even without explicitly running the verifier.

It looks like I have my work cut out for me! I'll update this thread with progress.

**Comment by dougalm** [comment]
Ok, I fixed the errors caught by the verifier here: 80f6f97f545d

In other good news, I managed to reproduce your build on a Mac and, after 80f6f97f545d, it passes the tests on it too!

**Comment by oxinabox** [comment]
Working now for me.
Awesome
