### ISSUE TITLE
Missing `splitDest` case for `Unpack` breaks top-level tables indexed by records

### ISSUE THREAD

**Issue by danieldjohnson** [google-research/dex-lang#207]
This:
```
recordsAsIndices : {a:Fin 2 & b:Fin 3}=>{a:Fin 2 & b:Fin 3} = for i. i
:p for i:(Fin 6). recordsAsIndices.((ordinal i) @ _)
```
fails with
```
dex: src/lib/Imp.hs:433:24-76: Non-exhaustive patterns in lambda
```
It looks like this is because `splitDest` doesn't support `Unpack` decls. As far as I can tell this only happens when the table is a top-level binding; inside a local let block this works fine.

**Comment by apaszke** [comment]
This should be fixed now.
