### ISSUE TITLE
Variable names are not reusuable, even if an error prevented them getting defined

### ISSUE THREAD

**Issue by oxinabox** [google-research/dex-lang#22]
Lets say I made a typo when assigning a value to a variable.
And so I get an error saying something on the RHS is not valid.

If I want to go and assign it again, I get an error saying that my variable has already been defined.

```
>=> x = 1 + 1
Type error:
Expected: Real
  Actual: Int
In: 1

x = 1 + 1
    ^^

>=> x
Error: variable not in scope: x
>=> x = 1.0 + 1.0
Error: variable already defined: x
>=> x
Error: variable not in scope: x
```

I am down with not allowing variables to be redefined.  
But I don't think erroring should count as defining.

I am thinking that the flag to mark a variable as defined or not needs to occur after it is determined that the RHS did not error.

**Comment by dougalm** [comment]
Yes, good observation. I'll push a fix in a sec. My only reluctance is that it breaks the principle that the REPL behavior should be the same as eval-whole-file behavior. So  we might revisit it in the future.

**Comment by oxinabox** [comment]
> My only reluctance is that it breaks the principle that the REPL behavior should be the same as eval-whole-file behavior.

Thinking about why I expected it to work in REPL but not in file:
I have an implict notion of a error handling context, I think.
Like a try-catch.
And when a error occurs, I expect it to crash out the the level of the error handling context.
And from there act like I had not entered the context in the first place.

So for a file, the size of that context is the whole file (and if had multifile programs it would be the whole program.).
But for a REPL, that context is just 1 cell.
