### ISSUE TITLE
Crash when building a list

### ISSUE THREAD

**Issue by duvenaud** [google-research/dex-lang#228]
Now that we have lists, I'm trying to write a ```filter``` function.  It looks like this used to be a language keyword, and I bet that would make sense for performance reasons, but in the meantime I wrote this:

```
def filter (cond:a->Bool) (xs:n=>a) : List a =
  emptytable = for i:(Fin 0). todo  -- can't use []
  emptylist = AsList 0 emptytable

  snd $ withState emptylist \list.
    for i:n.
      case cond xs.i of
        True -> list := get list <> AsList 1 [xs.i]
        False -> ()
```

This typechecks, but when I run it:
```
:p filter (\x. x > 2.0) [4.0, 0.0, 10.0, 2.0]
```
I get an error:
```
Mismatched dimensions in zipWithDest!
CallStack (from HasCallStack):
  error, called at src/lib/Imp.hs:616:47 in dex-0.1.0.0-IYxyzQADM8eGhInlFxB9Qk:Imp
```

Incidentally, I couldn't figure out a way to make an empty list without writing ```for i:(Fin 0). todo```, even when the compiler can infer its type.  There's a compiler message about how you need to annotate the type of ```[]```, but I couldn't guess the syntax, and it shouldn't be necessary in this instance.

**Comment by danieldjohnson** [comment]
`[]:(Fin 0 => _)` seems to work as an annotation, although inference should probably be able to write that for you...

**Comment by duvenaud** [comment]
D'oh, yes I should have been able to guess that syntax.  At first I was looking around for something like ```Absurd``` or ```Void``` before I realized I could just use ```Fin 0```.

**Comment by duvenaud** [comment]
This works now in the `dev` branch!  Here's some slightly cleaned-up `filter` code in case anybody needs it:

```
def filter (condition:a->Bool) (xs:n=>a) : List a =
  emptylist = AsList 0 []
  snd $ withState emptylist \list.
    for i:n.
      case condition xs.i of
        True -> list := get list <> AsList 1 [xs.i]
        False -> ()
```

**Comment by apaszke** [comment]
One small note though is that the implementation above has O(n^2) complexity, which we should definitely improve :)
