### ISSUE TITLE
Crash out from showing index

### ISSUE THREAD

**Issue by oxinabox** [google-research/dex-lang#23]
Similar to #17  I think, but this one still crashes

can get it from `asidx`
```
>=> kk::4 = asidx 4

>=> kk
dex: can't show 4
CallStack (from HasCallStack):
  error, called at src/lib/Imp.hs:176:12 in dex-0.1.0.0-9pQ6aTLha3fLdCjkbXPWRy:Imp
```

Can also get it out of `for`

```
>=> v = for ii::4 . ii

>=> v
dex: can't show 4
CallStack (from HasCallStack):
  error, called at src/lib/Imp.hs:176:12 in dex-0.1.0.0-9pQ6aTLha3fLdCjkbXPWRy:Imp
```

In both cases it fully crashes out to the shell

**Comment by dougalm** [comment]
In this case there's no reason not to be able to print indices. I pushed a fix.

I really appreciate these bug reports. Now that we have something like a typeclass system, it should be possible to get to a state where the only errors are clear type errors and clear "not implemented" errors.
