### ISSUE TITLE
Parser doesn't allow the binders in types to be wrapped in parens.

### ISSUE THREAD

**Issue by duvenaud** [google-research/dex-lang#236]
At the top level, creating triangular arrays works fine:
```
n = Fin 4
:t for j:n. for i:(..j). 1.0
((j:(Fin 4)) => (..j) => Float32)
```

But not inside a function or declaration:
```
func : _ =
  for j:n. for i:(..j). 1.0
Type error:Leaked type variable: j:?1

  for j:n. for i:(..j). 1.0
  ^^^^
```

It also doesn't appear to be possible to spell the type of a function that returns a triangular array, although it can be inferred if you use a ```_```.  Copying the output of ```:t``` above gives:
```
def func2 (a:Type) : ((c:a)=>(..c)=>Float32) =
  for j:a. for i:(..j). 1.0
Parse error:7:27:
  |
7 | def func2 (a:Type) : ((c:a)=>(..c)=>Float32) =
  |                           ^^^
unexpected ")=>"
expecting ''', '_', alphanumeric character, or arrow
```

While we're here, I also wish the "Leaked type variable" error message gave more details.

**Comment by duvenaud** [comment]
Update: You can spell the type, the parser just can't handle extraneous parentheses here.  If I remove the parentheses around ```c:a``` it works fine:

```
def func2 (a:Type) : (c:a=>(..c)=>Float32) =
  for j:a. for i:(..j). 1.0
```

**Comment by duvenaud** [comment]
Update 2:  Now that I can explicitly spell the type, I can declare a diagonal type inside a function just fine:

```
def func (a:Type) ?-> : (c:a=>(..c)=>Float32) =
  for j:a. for i:(..j). 1.0
```

So I think this is only a case of a too-conservative parser and bad error messages.

**Comment by apaszke** [comment]
I'll reopen this, because it looks like a legit issue with the parser, so let's track it!
