### ISSUE TITLE
Erroneous Type Leakage Error

### ISSUE THREAD

**Issue by duvenaud** [google-research/dex-lang#244]
I've been plagued by ```Leaked type variable``` errors lately.  These can be subtle, but I'm pretty sure I've identified a bug.

Here's a minimal example:
```
def notok (a:n) : Unit =
  snd $ withState () \s.
    for j:n.
      for i:(..j). ()
Type error:Leaked type variable: j:?8

    for j:n.
    ^^^^
```

At first I thought this was some subtle issue, perhaps with the type of ```withState```.  But if I add another line that does nothing, the error goes away:

```
def ok (a:n) : Unit =
  snd $ withState () \s.
    for j:n.
      for i:(..j). ()
      for i:n. ()
```
This gives no errors.  So I have a workaround for now, but it's unnerving.

**Comment by apaszke** [comment]
Another, simpler example:
```
id (for i:(Fin 10). for j:(..i). 1.0)
```
It looks like this is due to us being unable to infer the dependent type in checking mode, because the dependent parts get unified with inference variables that do not really push any information down.
