### ISSUE TITLE
grad crashes for withstate with a auxiliary table

### ISSUE THREAD

**Issue by duvenaud** [google-research/dex-lang#257]
I was fixing up the fluidsim demo and trying to differentiate through it, but caused a crash.  Here's a MWE:

```
def f (c:Float) : Float =
  v = for i:(Fin 2). 2.0
  (c, v) = snd $ withState (c, v) \r. for i:(Fin 2).
    (c, v) = get r
    r := (c + sum v, v)
  c

:p grad f 0.1
```
gives a crash:
```
Not a tangent atom: (\for _:(Fin 2). 0.0)
CallStack (from HasCallStack):
  error, called at src/lib/Autodiff.hs:704:22 in dex-0.1.0.0-CA4uXQ86C1yKMObiJn1rPk:Autodiff
```

**Comment by apaszke** [comment]
I think the example is incomplete (`f` is undefined). Can you please fix it?

**Comment by apaszke** [comment]
Though I know that this error can appear if your function has outputs that were not affected by any inputs, and you're trying to AD through it.

**Comment by duvenaud** [comment]
Whoops, the first line was eaten by the formatter because I didn't put a newline after the triple quotes.

I also updated the example to depend on the auxiliary variable.  The old version didn't depend on ```v``` but my actual use case does, and in any case the error is still there.
