### ISSUE TITLE
Please print all floating-point digits

### ISSUE THREAD

**Issue by axch** [google-research/dex-lang#28]
```
>=> 3.14159265
3.1415927
```

Sadness.

Dex represents floating-point numbers internally in Double precision, and AFAICT correctly parses inputs as such, but truncates to single precision on output [here](https://github.com/google-research/dex-lang/blob/master/src/lib/PPrint.hs#L95).  That was clearly done intentionally, but I think that choice should be revisited.

I see the rationales for printing all available digits to be as follows:
- Read-print and print-read invariance are desirable on general principle, and floating-point numbers need not violate them.
- In particular, the print-read invariance property test currently fails on doubles.
- Loss of information on print can be very confusing when trying to debug a program.

As an example of the consequences of not printing everything, this can happen:
```
>=> y > x
True
>=> [y, x]
[1.0, 1.0]
-- !!?
```
It's not even very hard to arrange:
```
>=> x = 0.99999999

>=> y = 1.0
```

Presumably the desideratum on the other side is avoiding overwhelming the user with excess or unwarranted precision, and also arranging for neat tabular output.  The latter can be arranged without loss of information, by padding to enough digits.

**Comment by axch** [comment]
One more reason to print all available digits: poor-man's serialization.

**Comment by dougalm** [comment]
Actually, the main reason to print in single precision (74f755564a65) was to make the quine tests consistent between my local machine and Travis. It's a hack but a very convenient one.

Separately, I do think that low-precision printing is a good thing, perhaps even as default. But there needs to be a convenient way to ask for results at a specified precision. Once we have that, we can easily make the quine tests less flaky by asking for low precision results in the tests themselves. Until then, f83138627d31c11a9b2b makes the generator only generate f32-representable floats.
