### ISSUE TITLE
Type checking failing for record-indexed tables.

### ISSUE THREAD

**Issue by duvenaud** [google-research/dex-lang#284]
I'm trying to implement array padding in a Dex-y style, while trying to avoid length-erased lists.  I think this might be a nice demo of records-as-index-sets, since the information needed to un-pad correctly is carried in the type.

Padding works fine:
```
def pad (x: n=>a) (m:Type) (pad_value: a) : ({vals:n | padding:m }=>a) =
  for i. case i of
    {| vals    = i |} -> x.i
    {| padding = i |} -> pad_value

:p pad [2.0, 3.0] (Fin 3) 0.0
[0.0, 0.0, 0.0, 2.0, 3.0]@{padding: Fin 3 | vals: Fin 2}
```

But un-padding runs into some sort of type unification error:

```
def unpad (x:{vals:n | padding:m }=>a) : (n=>a) =
  y:{vals:n}=>a = sliceFields #|vals x
  for i. y.{vals=i}

Type error:
Expected: ({vals: n} => a)
  Actual: ({vals: n} => a)

  y:{vals:n}=>a = sliceFields #|vals x
                  ^^^^^^^^^^^^^^^^^^^^
```

At the very least, the error message is maddening. :)

**Comment by dougalm** [comment]
We don't have index sets on variants anymore (because we have the user-level `Ix` class now and the alphabetical field ordering was always sketchy) but this works now, at least, which is the same sort of thing:
```
def pad {a n} (x: n=>a) (m:Type) [Ix m] (pad_value: a) : ((n|m)=>a) =
  for i. case i of
    Left i -> x.i
    Right _ -> pad_value

def unpad {m n a} [Ix n, Ix m] (x:(n|m)=>a) : (n=>a) =
  for i. x.(Left i)

```
