### ISSUE TITLE
Variables not introduced into scope in type declarations.

### ISSUE THREAD

**Issue by duvenaud** [google-research/dex-lang#285]
I'm starting to use lists, but almost every function in the prelude (such as `argmin`) takes in a table.  So I tried to write a function to cast a list to a table, un-erasing the length:

```
def listToTable ((AsList Length xs):List a) : (Fin Length)=>a = xs
```
(edited to use uppercase names as per @danieldjohnson 's suggestion).  However, this gives:
```
Error: variable not in scope: Length

def listToTable ((AsList Length xs):List a) : (Fin Length)=>a = xs
                                                   ^^^^^^
```

I'm not sure if what I'm asking for is trivial or undecidable, or what will be erased at compile time under what circumstances.  I'm also open to the idea that casting back to a table is always unnecessary.

Here are some related errors and dead ends I hit when trying to work around this.

First, I tried something that I was pretty sure wouldn't work, but I think is planned to be added, which is to get the length from a helper function that gets called as part of the return type definition:

```
def ListLength ((AsList length xs):List a) : Int = length
def listToTable2 (L: List a) : (Fin (ListLength L))=>a = xs
```
But this gives
```
Error: variable not in scope: L

def listToTable2 (L: List a) : (Fin (ListLength L))=>a = xs
```

I was able to get a version of this working, but at the cost of never being able to pass the resulting table out of a function.  This works fine:
```
def listToTableAmbiguous (list: List a) : n=>a =
  (AsList length xs) = list
  for i:n.
    xs.((ordinal i)@(Fin length))

def listsum' (list:List Float) : Float =
  length = listLength list
  table:((Fin length)=>Float) = listToTableAmbiguous list
  sum table
```

Bur I could already do the same thing more easily with
```
def listSum ((AsList length xs):List Float) : Float = sum xs
```

If I try to make a more general version, I can't type the function to be applied to the table:
```
def listReduce ((AsList length xs):List a) (f:n=>a->a) : a = f xs
Type error:
Expected: (n => a)
  Actual: ((Fin n1) => a)

def listReduce ((AsList length xs):List a) (f:n=>a->a) : a = f xs
                                                               ^^
```

**Comment by danieldjohnson** [comment]
I think that a lot of the errors are happening because Dex actually treats EVERY lowercase-starting identifier in a type as a universally quantified type, defaulted to have kind `Type`. You can probably get more specific errors by using uppercase aliases of the functions you are using.

Unfortunately, my guess is that even after that, it will still fail because of "can't reduce type expression" errors; Dex doesn't have very good support for types that are returned from (nontrivial) functions.

**Comment by duvenaud** [comment]
Thank you Daniel, you're right!  Pleasingly, the error message for my first attempt changed to `Error: variable not in scope: Length`.

As for the case-sensitivity, perhaps the fact that Dex can in principle allow this kind of in-line type-level programming should be a reason not to use case as a modifier.  For instance, I also had to change the name of `listLength` to `ListLength` in order to use it in the type of `listToTable2`.

**Comment by apaszke** [comment]
This is the same issue as in #286, so let's close it.
