### ISSUE TITLE
Automate generation of Github Pages

### ISSUE THREAD

**Issue by oxinabox** [google-research/dex-lang#291]
I looked at https://google-research.github.io/dex-lang/prelude.html
and saw it still showed `Float` as `Real`
I looked at the **gh-pages** branch and saw it had not been updated since August 10th.

I think something needs to be setup so that on a PR being merged  HTML renderings are updated in the **gh-pages** branch.
I am sure GitHub actions can do this.

**Comment by apaszke** [comment]
Yeah, I agree this should be handled by GitHub actions, but we didn't get to it just yet. It would be a great contribution if you're up for it!

**Comment by apaszke** [comment]
@dougalm might have more details as to how he generated those pages. IIRC it involved some manual modifications, but we can just check in a diff file that will be applied.

**Comment by dougalm** [comment]
The only manual modification is changing the parameters for the ray tracer. The checked-in version uses a low resolution so you see a result quickly if you run it.

Some of the examples (e.g. the ray tracer) take a while to run on a beefy machine, so they might not be a perfect fit for GH actions. Maybe we should set up GH actions for things like the prelude and lightweight examples and continue running the computationally intensive examples manually. That way we also wouldn't have to worry about applying a diff file.
