### ISSUE TITLE
Type error:Couldn't synthesize a class dictionary for: (Eq v)

### ISSUE THREAD

**Issue by oxinabox** [google-research/dex-lang#293]
I thought we had equality working for indexes

The following works:
```
:p (1@(Fin 2)) == (1@(Fin 2))
True
```

But when I go to use it in a function:
e.g. some `zeroDiag` with expexcted behavour:
`zeroDiag [[1.0 2.0], [3.0 4.0]] == [[0.0 2.0], [3.0 0.0]]`

I get an error:
```
def zeroDiag (x:v=>v=>Float): v=>v=>Float =
  for i. for j. select (i==j) 0.0 x.i.j
Type error:Couldn't synthesize a class dictionary for: (Eq v)

  for i. for j. select (i==j) 0.0 x.i.j
```

I am guessing I need to add some more annotations to help it work out what type `v` is.

But this used to work, which seems very similar
https://github.com/google-research/dex-lang/blob/8806d9be61fcc44fe52fa6d3e8339a8bd15f7aef/examples/chol.dx#L6-L7

**Comment by oxinabox** [comment]
Ahha, one nees to use the confused rocket emoticon to thell it that  it `v` is an ordinal type.

```
def zeroDiag (d:Ord v) ?=> (x:v=>v=>Float): v=>v=>Float =
  for i. for j. select (i==j) 0.0 x.i.j

:p zeroDiag [[1.0, 2.0], [3.0, 4.0]]
[[0.0, 2.0], [3.0, 0.0]]
```

**Comment by apaszke** [comment]
Technically just `Eq v` would be sufficient here. But yeah, it would be best if we did pull in some of those interfaces automatically for types that are used as array indices (all index sets have to have a well defined `Eq`, `Ord` and `Idx`)
