### ISSUE TITLE
Add a new loop construct just for side-effects

### ISSUE THREAD

**Issue by duvenaud** [google-research/dex-lang#295]
I'm making more progress on type-safe graphs, but hit a compiler bug when trying to iterate over lists.  Here's a minimal working example:
```
def countList (list: List n) : Int =
  snd $ withAccum \s.
    (AsList m xs) = list
    for j:(Fin m).
      s += 1
```
gives
```
Compiler bug!

Non-global free variable in module: n1
Checking module:
Module (Typed)
  unevaluated decls:
  tmp:((n2:Type) ?-> (List n2) -> Int32) =
.
.
.
```

I thought the problem might be due to unpacking an ADT inside a loop, but I don't think so, since this works fine:
```
def countEdges (lists:n=>List n) : Int =
  sum for i:n.
      (AsList m children) = lists.i
      m
```

If you're curious, here's the function that I originally tried to compile:
```
def childListsToEdgeList (lists:n=>List n) : List (n & n) =
  emptylist = AsList 0 []
  snd $ withState emptylist \list.
    for i:n.
      (AsList m children) = lists.i
      for j:(Fin m).
        list := get list <> AsList 1 [(i, children.j)]
```

**Comment by apaszke** [comment]
I think that #283 should have fixed it! I posted it a long time ago, but I forgot to merge it. This should work if you pull `dev` now. Well, with the exception that it will fail with a type error that you can fix by appending a `()` as the expression that follows that `for`, but at least the error should be descriptive now!

**Comment by duvenaud** [comment]
Thanks for the fast response!  #283 did indeed give better error messages, and I was able to fix my toy example, but not my real example.

On the toy example, adding `()` didn't change anything, but I was able to fix it by following the error message, making the leaked local variable non-local:

```
def countListfixed (list: List n) : Int =
  (AsList m xs) = list  -- moved this line up
  snd $ withAccum \s.
    for j:(Fin m).
      s += 1
```

However, I couldn't do the same thing in my real example, although I was able to add a hack to fix it.

To give details:  Adding `()` didn't do anything, which makes sense based on the error message:
```
def childListsToEdgeList (lists:n=>List n) : List (n & n) =
  emptylist = AsList 0 []
  snd $ withState emptylist \list.
    for i:n.
      (AsList m children) = lists.i
      for j:(Fin m).
        list := get list <> AsList 1 [(i, children.j)]
        ()
Type error:Leaked local variable `n1` in result type ((Fin n1) => Unit)

    for i:n.
    ^^^^
```

I tried making the leaked variable non-local, but I think I ran into some other type unification bug:
```
def childListsToEdgeList3 (lists:n=>List n) : List (n & n) =
  emptylist = AsList 0 []
  listlengths = for i.
    (AsList m children) = lists.i
    m
  snd $ withState emptylist \list.
    for i:n.
      m' = listlengths.i
      (AsList _ children) = lists.i
      for j:(Fin m').
        list := get list <> AsList 1 [(i, children.j)]
Type error:
Expected: (Fin n1)
  Actual: (Fin m')

        list := get list <> AsList 1 [(i, children.j)]
                                                   ^
```

But since the immediate error was caused by passing up a useless value whose type was leaking a local value, I simply wrapped the offending block in a useless `withState`, and that fixed the problem:

```
def childListsToEdgeList4 (lists:n=>List n) : List (n & n) =
  emptylist = AsList 0 []
  snd $ withState emptylist \list.
    for i:n.
      (AsList m children) = lists.i
      snd $ withState 0 \_.   -- This line eats the list of ()s
        for j:(Fin m).
          list := get list <> AsList 1 [(i, children.j)]
```

And that code works!

So my takeaway is:
1) I think there is still a type unification bug, but it's not blocking anything for me now.
2) The leaked variable checking might be stricter than necessary, but I can't think of a simple way to loosen it while maintaining correctness.  In the meantime we can just squash lists of `()` into a single `()` to avoid leaking local variables.

**Comment by apaszke** [comment]
Oh, so I didn't mean for you to put the `()` on the same nest depth as the assignment. Put it outside of the `for`! The leakage happens because you only want to evaluate the `for` for its side effects, but it still builds up a (fairly boring) value of `idx=>Unit` where `idx` is some expression which is local.

**Comment by duvenaud** [comment]
Oh, I see what you meant, that makes perfect sense!  And the error message gave me enough information to fix the bug, although my solution above wasn't as elegant as yours.

**Comment by apaszke** [comment]
Even if your code is fixed, I really don't like the fact that we often have this unit-at-the-end idiom to avoid leaking locals from fors that are executed purely for their effects. I wonder if we should also have `for_` or some similar builtin that would produce just a `Unit` to make sure that we don't end up accidentally leaking the iteration space. @dougalm WDYT?

**Comment by danieldjohnson** [comment]
I've run into something similar before as well. It's similarly annoying to iterate over all values in a particular range, since you have to first create the appropriate `Fin n` type, do index ordinal arithmetic, and then do the unit trick to get rid of that `Fin n` type you probably didn't want.

Maybe we could fix this in userspace, though, using lists? Something like
```
def foreach (lst: List a) (f: a ->{|eff} Unit) :{|eff} Unit =
  (AsList n xs) = lst
  for i:(Fin n). f xs.i
  ()

def countList (list: List n) : Int =
  snd $ withAccum \s.
    foreach list \_.
      s += 1
```
Currently this doesn't work because of #267, though.

**Comment by dougalm** [comment]
I think it's a great idea to have a `for_` that adds the unit constructor to the end of the body. It also documents that the loop is being executed purely for its effects. Implementation-wise, it would just be a parser rule.

**Comment by apaszke** [comment]
We could also play with other names like `foreach`, `loop`, `repeat`, `sequence` or other. `for_` is nice, but it might be a bit of a Haskellism, and we might be able to come up with something more readable for people unfamiliar with that.
