### ISSUE TITLE
Trouble running script

### ISSUE THREAD

**Issue by joaogui1** [google-research/dex-lang#3]
When I try to run `dex script foo` it always prints 

> When using the script command, you must provide a resolver argument
On the terminal screen and then does nothing. 
What's the correct syntax for running scritps with dex?
(Also maybe a related doubt, but what's the difference between .cd and .dx files?)

**Comment by joaogui1** [comment]
Ok, found a solution, just add quotes to the alias lol. Can someone answer me about the file types before I close this issue?

**Comment by dougalm** [comment]
Aha, so at least it builds in your case! (I'm still wondering how to solve #2.)

Glad you figured out the alias. I'll add the quotes to the readme.

The `.cd` extension is a holdover from an earlier version which was named "Coddle" (after [Edgar Codd](https://en.wikipedia.org/wiki/Edgar_F._Codd)). We recently renamed the project to "Dex". I see there's still a `.cd` file in the benchmarks file, which hasn't seen much love recently in any case. I'll update that too.

**Comment by dougalm** [comment]
Btw, thanks for the PRs. I need to set up the CLA bot like we have in JAX before I can start merging them. I'm sure you've realized, but the "benchmarks" directory is pretty half-hearted and hasn't been touched for a long time. I had just wanted to get a rough comparison of how this very naive compiler performs.

**Comment by joaogui1** [comment]
Oh, so you guys are not accepting PRs for that directory?

**Comment by dougalm** [comment]
I'm happy to merge small fixes but it's not a high priority

**Comment by joaogui1** [comment]
okss, got it
