### ISSUE TITLE
Crash with  Not implemented Float32 from src/lib/Embed.hs:744

### ISSUE THREAD

**Issue by oxinabox** [google-research/dex-lang#303]
I am not sure what i have done wrong,
but what every it is, it should give an error and not just crash the whole program.
This is with a fresh build of the dev branch.

```
>=> def countUses (d:Eq a) ?=> (needle:a) (haystack:n=>a) : Int =
...     fold 0 \x net. net + (BToI (x==needle))

>=> :p countUses 3.0 [1.0, 2.0]
dex: Not implemented Float32
CallStack (from HasCallStack):
  error, called at src/lib/Embed.hs:744:8 in dex-0.1.0.0-CA4uXQ86C1yKMObiJn1rPk:Embed
```

**Comment by oxinabox** [comment]
The code was wrong, but still it should not have crashed out.
Correct code is
```
>=> def countUses (d:Eq a) ?=> (needle:a) (haystack:n=>a) : Int =
...     fold 0 (\i net. net + (BToI (haystack.i==needle)))

>=> countUses 1 [1,2,2,1,1]
3
```

**Comment by dougalm** [comment]
Yes, terrible error. It's another instance of #186. I've been dragging my feet about fixing it because I'm unhappy about the way it's going to clutter up type signatures.

**Comment by oxinabox** [comment]
closing as duplicate of #186
