### ISSUE TITLE
Reading off the end of a table

### ISSUE THREAD

**Issue by axch** [google-research/dex-lang#31]
```
[1].(%asidx(9))
```
runs, and emits various interesting numbers, like 0, 18, 22, 183385288, and 139624557584448.  This should be at least a runtime error (though, for the literal case, compile-time might be nicer).

I am amused that the behavior is well-typed, e.g.
```
[(for c::4 . 5)].(%asidx(9))
```
emits things like `[179572448, 179571328, 4810363372640, 179613120]`, 
`[162423056, 162421936, 4810363372640, 162141280]`, `[1, 0, 0, 145]`, etc.

**Comment by oxinabox** [comment]
Yah, this is listed in `bugs.dx`

The notes there say it should wrap around, iirc. So like R.

It's unfortunate that it can't give a put of bounds error at compile time. (At least not in general, AFAIK)

**Comment by dougalm** [comment]
This now hard-exits the program. Ideally we'd be able to catch the error, at least at the top-level interpreter. But that will take a bit more work. There's also work to be done in deciding what semantics we actually want for runtime errors.

    >=> [1].(%asidx(9))
    Index out of bounds. 9 not in [0, 1)
