### ISSUE TITLE
Parsing functions for integers

### ISSUE THREAD

**Issue by oxinabox** [google-research/dex-lang#312]
It would be nice to be able to parse an integer out of a string.
I think its reasonable to implement this in dex.
It might make a good first issue.

Probably would want varients for `List Char` and for `n=>Char` 
e.g
```
>=>:p parseInt "123"
123

>=>:p parseIntL (AsList _ "123")
123
```

**Comment by dougalm** [comment]
Let's do parser combinators in Dex! It would be easy to build on top of the state effect and the exception effect. We just need to implement the exception effect ...
