### ISSUE TITLE
Unexpected zext from type conversion of negative Int32 to Int64

### ISSUE THREAD

**Issue by dan-zheng** [google-research/dex-lang#317]
Reproducer:
```console
$ dex repl
>=> -1234
-1234
>=> IToI64 (-1234)
4294966062 -- underflow?
```

One would probably expect ` IToI64 (-1234: Int32)` to return `-1234: Int64`, not `4294966062: Int64`.

**Comment by dougalm** [comment]
Oof. It's not underflow. It's that our `IToI64` is just doing zext (see [here](https://github.com/google-research/dex-lang/blob/main/src/lib/JIT.hs#L534) and [here](https://github.com/google-research/dex-lang/blob/main/src/lib/JIT.hs#L697)), so the sign bit of the I32 ends up as an ordinary bit of the I64.

```
>=> IToI64 (-1)
4294967295
```

(Note that 4294967295 = 2^32 - 1)
