### ISSUE TITLE
Pretty-print `n=>Char` tables as string literals

### ISSUE THREAD

**Issue by dan-zheng** [google-research/dex-lang#321]
It would be better to print `n=>Char` values as `"xyz"` string literals rather than the standard `['x', 'y', 'z']` format.

```console
$ dex repl
>=> :t "Hello world"
((Fin 11) => Char)
">=> "Hello world"
['H', 'e', 'l', 'l', 'o', ' ', 'w', 'o', 'r', 'l', 'd']
```

**Comment by dan-zheng** [comment]
I'll give this a shot tonight.

**Comment by apaszke** [comment]
FYI the printing you see there is not that of `UTabCon`, but `pprintVal` from `Serialize.hs`
