### ISSUE TITLE
Ord for tables

### ISSUE THREAD

**Issue by oxinabox** [google-research/dex-lang#324]
We have Ord for tuples,
I think we should have it for tables as well
so that one can sort them.

```
>=> [1, 2] < [10, 2]
Type error:Couldn't synthesize a class dictionary for: (Ord ((Fin 2) => Int32))

[1, 2] < [10, 2]
       ^^
```

**Comment by apaszke** [comment]
This should be possible to implement entirely in user-space in the same way equality for tables is defined.

**Comment by ananduri** [comment]
Hi, I'd like to take a crack at adding this. I have a question, though: how are tables defined? From the comment above about equality defined for tables in user space, I was thinking that there would be an instance for Eq defined in say the prelude. But I searched the codebase for `instance Eq`, and couldn't find one for a "Table" type, although I can see that Eq for Tables works in the REPL. Is there something I'm missing?

**Comment by oxinabox** [comment]
It is here:
https://github.com/google-research/dex-lang/blob/85ff5167e31bef734ef13552d6aad6524dc0dfc5/lib/prelude.dx#L351-L357


The table type is written `a=>b` for some index type variable `a` and value type variable `b`.

**Comment by ananduri** [comment]
Thanks for the reference oxinabox! I made a PR implementing this at https://github.com/google-research/dex-lang/pull/455. Hope it gets the job done, and open to any pointers on the code.

**Comment by dan-zheng** [comment]
Thank you Arun! I see that we're fellow Googlers :)

I had just one question about your implementation: https://github.com/google-research/dex-lang/pull/455#discussion_r556551481

**Comment by dan-zheng** [comment]
Done by @ananduri in https://github.com/google-research/dex-lang/pull/455 - thanks and welcome!

**Comment by dan-zheng** [comment]
@ananduri: would you be interested in any other starter tasks? There are many interesting categories of work:
* Tutorials and documentation
* Tooling: notebooks and editors
* Compiler stuff: optimizations and backends
* Language features

This goes out to all Dex project followers and lurkers. If you share a bit about your background and interests, I'm happy to help recommend some starter tasks for you! Feel free to reply here, or email me at danielzheng@google.com.

**Comment by ananduri** [comment]
Dan: Glad you asked. I would most definitely be interested. I'll send you an email at your google address about this soon.
