### ISSUE TITLE
Awesome Isometric DEX Logo?

### ISSUE THREAD

**Issue by jessebett** [google-research/dex-lang#326]
Will DEX have its own [awesome isometric logo](https://raw.githubusercontent.com/google/jax/master/images/jax_logo.svg)?

**Comment by apaszke** [comment]
Maybe! Once someone figures out a good way to lay out the letters 😛

**Comment by oxinabox** [comment]
![XLA](https://user-images.githubusercontent.com/5127634/101784004-daa9f480-3af2-11eb-98ff-0a7a83730ab9.png)
![JAX](https://raw.githubusercontent.com/google/jax/master/images/jax_logo.svg)

**Comment by jessebett** [comment]
Ah @oxinabox I looked for the XLA logo for a while with no success.

**Comment by jessebett** [comment]
I think it would be cute if one of the DEX cubes looks as though it's being `getindex`'d out of the logo. Not sure what that should exactly mean aesthetically.

**Comment by dan-zheng** [comment]
[Isometric font buffet:](https://www.fontspace.com/category/isometric)

<details>
<p>

<img src="https://user-images.githubusercontent.com/5590046/102688200-17e14700-41c3-11eb-9fc1-6518ad571b0f.png" alt="'Dex' in isometric fonts" width="80%"/>)

</p>
</details>

Logo aside: I'm a big fan of the 🔢 emoji for Dex. It's a small table of numbers/indices!

# 👩‍💻 🔢 👨‍💻

**Comment by apaszke** [comment]
The first one is kind of cool. It's a triangular array!

**Comment by apaszke** [comment]
Adding a logo would be amazing, but I'm closing this so that we can use issues for development-related tasks! Thanks!
