### ISSUE TITLE
Checking if a value is within the range of a indexset

### ISSUE THREAD

**Issue by oxinabox** [google-research/dex-lang#333]
If I have for example an integer `x` and an indexset `n`
then if `n` is a `Fin _` i can check if `x@n` will work via `x >=0 && x < size n`.
But thsi won't work if `n` is a `Range _ _`.
or some other indexing type

**Comment by apaszke** [comment]
Can you please give us some examples to show how would that be useful?

**Comment by apaszke** [comment]
Right, but in that case your index is simple a `Range low high`. I think it might make sense to have an `inBounds :: Range low high -> Bool` function in the language, but I don't think that the same would generally be useful for other index sets (e.g. records or tuples)

**Comment by apaszke** [comment]
I'm not really sure what's the follow up for this, so I'm closing the issue. I think that you could implement this functionality for your own definition of "in range" using type classes. Feel free to reopen/continue the discussion if you really do care about something like that.
