### ISSUE TITLE
Debug Println

### ISSUE THREAD

**Issue by oxinabox** [google-research/dex-lang#335]
It would be really useful to have some form of `println` `debuglog` that did printing for debugging purposes.
Even if it didn't run under some (documented) circumstances

**Comment by dougalm** [comment]
Yes, this is a must-have. Like Haskell's `trace`, we'll want it to be something that bypasses the typed effect system so that you can add debugging prints anywhere. This means we'll have to be careful that the compiler doesn't delete it as dead code. Haskell's `trace` solves that by asking the user to set up a pretend data dependence. It makes it a bit of a pain to use but it could be a good place to start. We could make a first version using the C FFI.

**Comment by oxinabox** [comment]
Can we disable dead code elimination in the compiler?
Then it would only be certain to show up in debug mode?

**Comment by apaszke** [comment]
We could just special case this primitive in dead code elimination, so I wouldn't worry about that particular pass too much. The overall interaction with the system is what concerns me, but to be honest I can't think of too many places where we would drop such instruction.

**Comment by dougalm** [comment]
> We could just special case this primitive in dead code elimination

That might get harder once we have runtime (i.e. non-inlined) functions because it could be the function application that gets detected as dead code rather than the primitive itself. In any case, there are plenty of ways to fix it.

**Comment by apaszke** [comment]
One way to do this would be to have a richer internal effect system. This would also be useful for e.g. computation that might abort, since parallelization needs to take that into account.

**Comment by dougalm** [comment]
I think #367 fixes this. The idiom would be something like this:

```
def myBuggyReverse (xs:n=>Int) : n=>Int = unsafeIO do
  for i.
    i' = size n - ordinal i - 2
    print $ "index is: " <> show i'
    xs.(i'@_)

:p myBuggyReverse [1,2,3]
> index is: 1
> index is: 0
> index is: -1
> Ordinal index out of range:-1 >= 3
> Runtime error
```

You need to put the `unsafeIO` around the whole function body - if you just put it around the print, then it will get DCEd.

Let me know if it works for you!

**Comment by oxinabox** [comment]
It does work. 
Very cool.

**Comment by dougalm** [comment]
Currently it doesn't print anything until the computation has finished. So you can't use it to monitor a long-running computation. Fixing that is somewhere on my todo list, so let me know if it would be helpful.

**Comment by oxinabox** [comment]
As long as it still prints if the computation RunTime errors i think it doesn't matter if it waits til it is done.
(or rather its low priority making it print sooner)
