### ISSUE TITLE
:time to measure timing?

### ISSUE THREAD

**Issue by oxinabox** [google-research/dex-lang#341]
I would like a way to benchmark code.

It might be nice if
```
:time foo 1
```
would print out how long that operation took.

I though this was already a thing, but I can't find it anywhere in the source.

**Comment by dougalm** [comment]
Yes, we changed it. It now looks like this:

```
%time
x = sum for i:(Fin 1000000). hash (IToI64 0) (ordinal i)
>
> Compile time: 81.599 ms
> Run time:     9.962 ms 
```

**Comment by apaszke** [comment]
But you should never use `%time` to benchmark code! Use `%bench "benchmark name"` instead!

`%time` only ever runs your code once, so I wouldn't trust the result if your function is cheap (on the order of microseconds or less)!
