### ISSUE TITLE
Custom jvp, defjvp 

### ISSUE THREAD

**Issue by srush** [google-research/dex-lang#354]
Was just curious if this was exposed. I use this a lot in torch/jax.

**Comment by dougalm** [comment]
We had a version of custom derivatives some time ago but it atrophied. We should revive it! Let's use this issue to track it.

The version we had only worked for first-order top-level functions. Would that cover most of your use cases?

**Comment by srush** [comment]
I think so? Or probably could make that work. 

There is no rush. just a cool feature to have.

**Comment by dougalm** [comment]
Closing this, since @apaszke added custom linearization a little while ago.
