### ISSUE TITLE
Flesh out the @noinline feature

### ISSUE THREAD

**Issue by apaszke** [google-research/dex-lang#361]
This is now part of the language (as of #349), but is only used in internal libraries and will generally provide a very poor UX. A list of known limitations:
- [x] Use of `GlobalName`s for noinline functions, instead of `TopLevelName`s
- [x] interactions with AD are unclear
- [x] no support for curried functions
- [x] *(low priority)* support for polymorphic functions

**Comment by dougalm** [comment]
Done on all counts!
