### ISSUE TITLE
Support better syntax for interface constraints

### ISSUE THREAD

**Issue by apaszke** [google-research/dex-lang#370]
Right now we don't have any special syntax for interface _binders_, which forces everyone to write an underscore in that place:
```
def anotherAdd (_:Add a) ?=> (x: a) (y: a) : a = x + y
```
We should make it more streamlined. Here is one potential syntax, but I'm open to other suggestions as well:
```
def anotherAdd Add a ?=> (x: a) (y: a) : a = x + y
```
The above might make the parser a little confusing, so we might want to consider using a visible delimiter for those args (and perhaps hide the awkward arrow?).

**Comment by duvenaud** [comment]
Are these syntax examples missing the function name?

**Comment by apaszke** [comment]
Yes, they are

**Comment by dougalm** [comment]
This is crucial for #186 too. Even if we do some constraint inference, we'll still be adding many more constraints than we have now.

Let's find something that doesn't require a new `?=>` for each additional constraint. Throwing out more possibilities:

```haskell
-- before args, special parens
def sum [Ix n, Add v] (xs:n=>v) : v = ...
```

```haskell
-- after args, delimiter keyword
def sum (xs:n=>v) : v where Ix n, Add v = ...
```
