### ISSUE TITLE
Document in tutorial the lack of loops and  branchs

### ISSUE THREAD

**Issue by oxinabox** [google-research/dex-lang#38]
As far as I can tell dex does not have branchs.
Instead on should just compute both sides,
and then use `select`.

Similarly there are not any loops.
This is common for functional languages, but the normal solution of using recursion doesn't work as without branches one can never stop recursing.
Instrad one should use `fold`.
(And maybe `scan` / `scan'`?)

**Comment by dougalm** [comment]
Closing because (1) we've removed the tutorial :) (it was too hard to maintain as we change the language) and (2) we have loops and branches now!
