### ISSUE TITLE
Can't use Unicode in function name?

### ISSUE THREAD

**Issue by oxinabox** [google-research/dex-lang#41]
What is this, 2003?

### works
```
>=> s:: Real->Real
... s x = 1.0/(1.0 + exp (neg x))

>=> :p s 0.0
0.5
```

### errors
```
>=> σ:: Real->Real
... σ x = 1.0/(1.0 + exp (neg x))
Parse error:2:1:
  |
2 | σ x = 1.0/(1.0 + exp (neg x))
  | ^
unexpected 'σ'
expecting 'Ã'

>=> :p σ 0.0
Error: variable not in scope: Ã
```

Weirdly the error message refers to `Ã` but the variable was `σ`.
I am guessing this is something like the input being read as Latin1 or something like that, rather than UTF8, as all modern things should be.

**Comment by dougalm** [comment]
Agreed. There's no reason not to support unicode. I'll look into the bug and add some tests for unicode variable names.
