### ISSUE TITLE
Implement the Language Server Protocol (LSP) for Dex

### ISSUE THREAD

**Issue by apaszke** [google-research/dex-lang#414]
The Language Server Protocol (LSP) is a protocol used between languages and IDE-like tools to provide language-aware IDE features, like jump-to-definition, find-all-references, and code completion.

It would be great for Dex to have LSP support: this could be used to implement a Visual Studio Code extension or Emacs mode for Dex, or to augment `dex web <file.dx>` with language-aware features like hover tooltips showing the types of variables and all references of a variable.

We're brainstorming some grander ideas for redesigning the Dex compiler to be more query-evaluation-oriented and API-oriented, and an LSP implementation overlaps with that vision. There's more design work and discussion to do, so we're not ready to start any implementation yet.

## References

* [Language Server Protocol homepage](https://microsoft.github.io/language-server-protocol/): overview, specification, and implementations
* [`haskell-lsp` library](https://hackage.haskell.org/package/haskell-lsp): for _implementing_ LSP for languages written in Haskell
* [Draft LSP implementation for the Koka language via `haskell-lsp`](https://github.com/koka-lang/koka/pull/100): <1000 lines in changes

_Originally posted by @dan-zheng in https://github.com/google-research/dex-lang/discussions/375_

**Comment by general-rishkin** [comment]
What is the status of the LSP? 
Is there a temporary alternative in the meantime, e.g., for vim or gedit, etc?

**Comment by apaszke** [comment]
@sharadmv wrote [dex-vim](https://github.com/sharadmv/dex-vim), but it only does syntax highlighting

**Comment by general-rishkin** [comment]
Excellent. That something at least. Thanks.

**Comment by dan-zheng** [comment]
Subsumed by https://github.com/google-research/dex-lang/issues/1304: adding tooltips to `dex web`.
