### ISSUE TITLE
matmul

### ISSUE THREAD

**Issue by oxinabox** [google-research/dex-lang#42]
It would be nice to have matrix multiplication defined.
Or possibly an interface for tensor-contractor / einsum.

I am assuming one does not want too do that inside Dex itself,
as it wants to hit some BLAS.
(or what ever XLA is doing in this space)

**Comment by oxinabox** [comment]
Oh this is defined in 
https://google-research.github.io/dex-lang/regression.html
with a note saying it should probably be in the prelude.
I agree with that note

**Comment by dougalm** [comment]
Yes, let's put it in the prelude.

> I am assuming one does not want to do that inside Dex itself, as it wants to hit some BLAS.

Eventually I'd like a pure-Dex matmul, perhaps with some Halide-style schedule specifications, to be competitive with BLAS implementations. But I'm planning to add array support to the FFI (it's currently scalar-only) so that we can use BLAS in the near term.
