### ISSUE TITLE
Render LaTeX equations in web notebooks

### ISSUE THREAD

**Issue by apaszke** [google-research/dex-lang#426]
Sounds like a pretty useful feature to have in a computing environment if you ask me.

**Comment by dan-zheng** [comment]
I've started looking into this! Supporting LaTeX snippets seems straightforward using [Pandoc](https://hackage.haskell.org/package/pandoc):

```haskell
markdownToHtml :: String -> Either P.PandocError Html
markdownToHtml s = P.runPure $ do
  let latexExtensions = P.getDefaultExtensions "commonmark_x"
  let readerOptions = P.def {
                        P.readerExtensions = latexExtensions
                      }
  let writerOptions = P.def {
                        P.writerExtensions = latexExtensions,
                        P.writerHTMLMathMethod = P.KaTeX P.defaultKaTeXURL
                      }
  let markdownText = strip (pack s) -- stripping leading whitespace is important for correctness
  markdown <- P.readMarkdown readerOptions markdownText
  result <- P.writeHtml5 writerOptions markdown
  return result
```

Pandoc is unfortunately quite large as a dependency, but that seems acceptable.

Still need to figure out how to appropriately hook into KaTeX so that `renderMathInElement(document.body)` fires at the right time (after the DOM has loaded). I tried listening for the `DOMContentLoaded` event, but it doesn't work yet [(code from here)](https://katex.org/docs/autorender.html#usage):

```html
<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/katex@0.12.0/dist/katex.min.css" integrity="sha384-AfEj0r4/OFrOo5t7NnNe46zW/tFgW6x/bCJG8FqQCEo3+Aro6EYUG4+cU+KJWu/X" crossorigin="anonymous">
<script defer src="https://cdn.jsdelivr.net/npm/katex@0.12.0/dist/katex.min.js" integrity="sha384-g7c+Jr9ZivxKLnZTDUhnkOnsh30B4H0rpLUpJ4jAIKs4fnJI+sEnkvrMWph2EDg4" crossorigin="anonymous"></script>
<script defer src="https://cdn.jsdelivr.net/npm/katex@0.12.0/dist/contrib/auto-render.min.js" integrity="sha384-mll67QQFJfxn0IYznZYonOWZ644AWYC+Pt2cHqMaRhXVrursRwvLnLaebdGIlYNa" crossorigin="anonymous"></script>
<script>
    document.addEventListener("DOMContentLoaded", function() {
        renderMathInElement(document.body, {
            // ...options...
        });
    });
</script>
```

**Comment by dougalm** [comment]
I love Pandoc and I use it all the time as a standalone executable. But we might be prevented from using it in Dex for licensing reasons: it's GPL. There's a thread about it here: https://github.com/jgm/pandoc/issues/180

**Comment by oxinabox** [comment]
I am kind of surprised this can't be done purely in the front end with MathJax/KaTeX searching over the content looking for `$\latex$` and rewriting.

**Comment by dan-zheng** [comment]
You're totally right oxinabox@, this is possible just via KaTeX on HTML-rendered Dex. I should have it ready soon, thanks!

**Comment by dan-zheng** [comment]
Done in https://github.com/google-research/dex-lang/pull/444.

Two example programs using LaTeX:

<details>
<summary>Monte Carlo simulations of pi</summary>
<img width="975" alt="Monte Carlo simulations of pi" src="https://user-images.githubusercontent.com/5590046/104080096-1fa96f80-51f4-11eb-9a5c-6fd024a3bc72.png">
</details>

<details>
<summary>LaTeX rendering examples</summary>
<img width="914" alt="download" src="https://user-images.githubusercontent.com/5590046/104080267-f2a98c80-51f4-11eb-90a4-78ceff85bd70.png">
</details>

**Comment by dan-zheng** [comment]
There's a bug: we should disable KaTeX rendering for HTML-rendered Dex code.

<img width="359" alt="KaTeX for Dex bug" src="https://user-images.githubusercontent.com/5590046/104087142-957cfd80-522b-11eb-9282-79025c6c4b41.png">

If KaTeX does not have direct support for such filtering, we can implement it in JavaScript (only calling `renderMathInElement` for the non-code HTML elements within which we want to render LaTeX).

**Comment by apaszke** [comment]
Can't we wrap the literate blocks in some common class and only render the content of those?

**Comment by dan-zheng** [comment]
> Can't we wrap the literate blocks in some common class and only render the content of those?

Exactly. This was done/fixed in https://github.com/google-research/dex-lang/pull/447, sorry that I forgot to provide an "issue resolved" update.
