### ISSUE TITLE
Add FileCheck tests for optimizations

### ISSUE THREAD

**Issue by apaszke** [google-research/dex-lang#428]
Optimizations like to regress a lot when we add new features to the language (which is all of the time). We already have an LLVM dependency, and [FileCheck](https://llvm.org/docs/CommandGuide/FileCheck.html) seems like a good tool to write robust tests that verify the different IR rewrites we apply.

**Comment by apaszke** [comment]
Good candidate for a regression test: #346

**Comment by axch** [comment]
We now have both (some) FileCheck tests and a matmul benchmark, so this is done.
