### ISSUE TITLE
Allow linebreak (..) in type-signature line

### ISSUE THREAD

**Issue by oxinabox** [google-research/dex-lang#45]
It would be nice to be able to put line breaks in the type signature.

e.g.

```
apply2Net:: ((hz=>(iz=>Real), hz=>Real), (oz=>(hz=>Real), oz=>Real)) -> iz=>Real -> oz=>Real
apply2Net (layer1, layer2) input = 
    sigmoid $ applyAffine layer2 $ sigmoid $ applyAffine layer1 input
```
vs
```
apply2Net:: ( ..
    (hz=>(iz=>Real), hz=>Real), ..
    (oz=>(hz=>Real), oz=>Real)..
    )..
    -> iz=>Real ..
    -> oz=>Real
apply2Net (layer1, layer2) input = 
    sigmoid $ applyAffine layer2 $ sigmoid $ applyAffine layer1 input
```

This also showed up in 
https://github.com/google-research/dex-lang/pull/33/files#diff-f3df4243876e24a9f40bddc8ba8ae4d9R67

**Comment by dougalm** [comment]
This should work. I'll look into what's going wrong.

**Comment by dougalm** [comment]
Ah, the problem is that you need a space between the closing paren and the dots in `)..`

The error message could definitely be better.
