### ISSUE TITLE
Revive the vector types

### ISSUE THREAD

**Issue by apaszke** [google-research/dex-lang#463]
A simple first step towards getting #416. We used to have vector types in the language, which let us at least compile efficient manual implementations of matmul (see `examples/tiled-matmul.dx`). Unfortunately, we've deleted them in one of our refactors, but we should bring them back now. They still exist in the compiler and should be handled correctly. The frontend bindings are the biggest missing piece.

Bonus points for making the vector types parametrized by an int that indicates their width. The previous implementation always assumed 8 elements which is bad.

**Comment by dan-zheng** [comment]
Are these LLVM-supported SIMD vector types?

**Comment by apaszke** [comment]
Yes, they do get lowered to LLVM vector types eventually.

**Comment by srush** [comment]
I'll give this one a try next. I think I mostly get the tiled example. 

 My understanding from the matmul example is that it partitions the index space and calls fTile on each region. Could someone explain to me the fScalar arg to tile though? 

```
def tile (fTile : (t:(Tile n l) -> {|eff} l=>a)) (fScalar : n -> {|eff} a) : {|eff} n=>a
```

**Comment by apaszke** [comment]
The `fScalar` is used for the trailing elements that are too small to fit in the tile (it's the "last batch" problem 😉). For example, if you tile `Fin 12` by `Fin 5`, `fTile` will be called twice (for tiles `0..<4` and `5..<10`) and `fScalar` will also be called twice (for indices `10` and `11`).

**Comment by srush** [comment]
@apaszke Just want to confirm my plan here before I start diving in.

There was an old Vector type that did operations only on VectorWidth(=hardcoded to 4) Float32, which could be optimized, particularly in conjunction with Tile (although the two are not connected).

This was removed from the front-end of Dex and replaced with a bunch of "Not Implemented" errors. 

My plan is to :

* Expose Vector for different scalar types
* Add front-end code for vector binops mirroring scalar binops. 
* Generally try to make Vector work in places where Scalar can.
* (Opt.) Try to generalize to different vector widths (Is that what you meant?)

When this is done Matmul should be fast, and possibly, I can try writing a non-slow convolution.

I'm going to try to do this from scratch, but likely fail and ask for help.

**Comment by apaszke** [comment]
Yes that sounds right! Note that there should be only a few operations specific for vectors (mostly packing/unpacking), and all math operators should just be handled by the right type classes.

One really important message: I would recommend waiting a few days before you start. The reason why the repo is so quiet at the moment is because @dougalm is working on an overhaul of the compiler that will touch almost every single line (but will give us nice type safety!). Applying any changes now will likely lead to conflicts with Dougal's patch, so feel free to try things out, but I think that we're freezing the code for now anyway.

**Comment by srush** [comment]
Wow, I thought I kind of knew haskell, but touching the internals of this compiler is a different level. It's been a couple years so extensions like bidirectional view patterns caught me off guard.

Now I want to do this more though, but I might just try writing some docs first as I catch up.

**Comment by apaszke** [comment]
Docs sound great too! Feel free to forward them if you'd like someone to check them.
