### ISSUE TITLE
Add syntax for explicit application of implicit arguments

### ISSUE THREAD

**Issue by apaszke** [google-research/dex-lang#464]
Dex has (not really, but for the purpose of this note) two kinds of arguments: implicit and explicit. Each one of those has its own abstraction rules, and explicit arguments can even be made implicit. But we can't go the other way around, even though it would be useful at times. 

```
myExplicitFunc x    -- explicit args can be specified as usual
myExplicitFunc _    -- explicit args can be made implicit by the use of underscore
myImplicitFunc      -- implicit args can be omitted
myImplicitFunc ???  -- cannot specify implicit arguments explicitly
```

Basically, whenever a function can _ever_ be used in a setting where its argument would be ambiguous we _have to_ make it explicit, adding noise to all the other call sites where it could be implicit. We should make it possible to just choose the strategy that fits the user the best and always make it possible to override those.

One syntax proposal: `myImplicitFunc {x}`. We could even make it so that implicit args also get defined by curly braces:
```
def myFunc {implicitArg: Int} (explicitArg: Float) : Float = ...
```

In the future, we could even make it possible to specify implicit args by name, i.e.
```
myFunc {implicitArg=2} 4.0
```

**Comment by dougalm** [comment]
Being able to specify them by name (like Idris) is probably important because the order of implicit args is often left unspecified. When you write `swap : (a & b) -> (b & a)` is the `a` first or the `b`?

**Comment by danieldjohnson** [comment]
Since the implicit args are technically ordered in the type signature, I think it would work fine to start with specifying by order, first-arg-first. I guess the confusing thing is that implicit-implicit-args aren't ordered by the user, they are ordered by the compiler? But we could have some guarantee about what order the compiler puts them in.

If you wanted to specify the values in a different order, you could always call it like `swap { _ b } ...` and let the compiler infer `_` using the existing logic. So it seems like a first implementation that was based on ordering would be possible.

**Comment by danieldjohnson** [comment]
Oh, but we have to be careful because `{x}` will be parsed as a record! And we want to be able to call functions with records. So maybe a different syntax is necessary.

**Comment by axch** [comment]
Idris uses `@{ ... }` for passing explicit named instances.  Maybe we can steal that syntax.

**Comment by apaszke** [comment]
I'm ok with that syntax, but we already use `@` as an alias of `fromOrdinal`. Another thing to take into account, would be to keep forward compatibility of any syntax we choose with named/labeled arguments. Apparently [OCaml supports those](https://v2.ocaml.org/manual/lablexamples.html) and we should try too.

**Comment by axch** [comment]
The syntax reorg in https://github.com/google-research/dex-lang/pull/1250 fixed this.  Implicit arguments can now be passed with keyword argument syntax (name=expr).
