### ISSUE TITLE
Parametric type aliases

### ISSUE THREAD

**Issue by oxinabox** [google-research/dex-lang#48]
Type signatures could be much clear if we had a way to define parameterized types with newtype.

From #47:
which has:
```
eval2NetLoss:: (oz=>Real->oz=>Real->Real) -> oz=>Real -> iz=>Real -> ((hz=>(iz=>Real), hz=>Real), (oz=>(hz=>Real), oz=>Real)) -> Real
```

if we had `{x}` do just basic templatish replacement:

This could be
```suggestion
newtype Layer{i,h} = (h=>(i=>Real), h=>Real)
newtype LossFunc{y} = (y=>Real->y=>Real->Real)

eval2NetLoss:: LossFunc{oz} -> oz=>Real -> iz=>Real -> (Layer{iz,hz},Layer{hz,oz}) -> Real
```

Related to #45

**Comment by dougalm** [comment]
Yes, we definitely want this. And it shouldn't be hard to add because type alias expansion is just a preprocessing step.

**Comment by oxinabox** [comment]
I am trying to workout how to use this.
It would be nice if it had a test I could copy

**Comment by oxinabox** [comment]
AH, got it:
```
type Layer d n = (d=>n=>Real, d=>Real)
```
