### ISSUE TITLE
Can't define Void type

### ISSUE THREAD

**Issue by duvenaud** [google-research/dex-lang#492]
This would be useful for the simplex demo, but the standard definition doesn't parse:

```
data Void =
  -- nothing here
```

Hardcoding `Void` through the compiler might be easier to implement than changing the parser to support this corner case.

**Comment by dougalm** [comment]
Good idea. The parsing rule would be easy to add, but we probably assume that constructor lists are non-empty in various places in the compiler. A built-in `Void` type would be easy to add too. Did you try other encodings, like `Fin 0`, or `{|}`?

**Comment by danieldjohnson** [comment]
I suppose you can always do
```
data Void = ImpossibleMkVoid {|}
```

**Comment by duvenaud** [comment]
`Fin 0` works, thanks guys!

I had also tried `data Void = {|}` but now see I should have written @danieldjohnson 's version.  That way parses, but doesn't seem to work:

```
data Void = ImpossibleMkVoid {|}
:p size Void
```
gives
```
Not implemented Void
CallStack (from HasCallStack):
  error, called at src/lib/Builder.hs:843:20
```

**Comment by danieldjohnson** [comment]
Indeed, my version defines an ADT but ADTs don't (yet) work as index sets. (Whereas both `Fin 0` and `{|}` alone do work as index sets.)
