### ISSUE TITLE
Haskell interface to the Dex compiler

### ISSUE THREAD

**Issue by joaogui1** [google-research/dex-lang#500]
So, the question is pretty much in the title, does dex act like a Haskell DSL that can be loaded into haskell code?

**Comment by apaszke** [comment]
We're pretty liberal with visibility rules for our modules, so I wouldn't be surprised if you could get it to work. Having said this, we definitely didn't design with that in mind and all our modules live in top-level namespace, so I would not recommend this. I'll leave this open as a feature request, but I wonder what was your use case?

**Comment by joaogui1** [comment]
I like using "standard" notebooks, so I was going to use iHaskell to code in dex
