### ISSUE TITLE
`make tests` segfaults if Fashion MNIST files are missing

### ISSUE THREAD

**Issue by perimosocordiae** [google-research/dex-lang#506]
After installing dependencies and running `make` successfully, I tried `make tests` and encountered a segfault in `tests/tutorial.dx`:

Output truncated to the last few lines:
```
misc/check-quine examples/chol.dx stack exec         dex -- script --allow-errors
OK
misc/check-quine examples/fft.dx stack exec         dex -- script --allow-errors
OK
misc/check-quine examples/tutorial.dx stack exec         dex -- script --allow-errors
misc/check-quine: line 31: 220729 Segmentation fault      (core dumped) ${@:2} $1 > $tmpout 2> $errout
make: *** [makefile:122: run-examples/tutorial] Error 139
```

After looking at the source a bit I found the instructions to download the Fashion MNIST files. Once those were in place, the segfault no longer happened.

Platform: Ubuntu 20.10 64-bit

**Comment by srush** [comment]
This is my fault. @dougalm is there a way to check if a file is exists?

**Comment by apaszke** [comment]
I don't think we have any way to do that right now. We should add a function to the standard library

**Comment by srush** [comment]
Great, I see that this is merged. 

@apaszke Any preferences on the right way to gate a section of code? Putting it in an `if` breaks top-level print. I could just create random images if the file doesn't exist, or just throw an error to prevent segfault?

**Comment by apaszke** [comment]
Actually `openFile` now throws an error, so at least it shouldn't crash the whole compiler. But, if you wanted to, we could have an `if hasFile` that raises a more friendly message.

**Comment by srush** [comment]
Oh that works. So maybe we should just close this issue.

**Comment by perimosocordiae** [comment]
The segfault is indeed gone, and the error message indicates which file is missing, so I'm happy to close this now.
