### ISSUE TITLE
Updating prelude.dx or dynamic.js or style.css and running make does not update

### ISSUE THREAD

**Issue by oxinabox** [google-research/dex-lang#519]
I am not sure if this is a Mac thing.
but it seems that if something is changed in `lib/prelude.dx`
then those changes are not reflected when next running Dex.
Nor do they change if you run `make`.
You need to run `make all`.

Same thing happens for `dynamic.js`,  and `style.css` which are copied into the static HTML pages if you do `make docs`.
But if you update it, and run `make docs` the old one will still be inserted 
You need to run `make all` first, then `make docs`
(not `make clean` only `make all` seems to do it)

It might be that this is related to https://github.com/haskell/cabal/pull/6889
since we are using an old version of cabal

**Comment by duvenaud** [comment]
Pretty sure this is fixed now.

**Comment by dougalm** [comment]
Assuming this is fixed (though I can't test on macOS). Closing for now.
