### ISSUE TITLE
What is the plan for structured sparse matrixes?

### ISSUE THREAD

**Issue by oxinabox** [google-research/dex-lang#53]
in #50 we really wanted a lower triangular matrix.
But we had to use a fully dense matrix.

One thing I felt while writing it, was if the iteration with nested `for` was somehow knowing of all the indexs (since structured sparse is basically characterized purely by indexes for a user facing perspective) then that might be it.
But those are two seperate for-loops right now.

More broadly, structured sparse matrixes don't play nice with the concept of a matrix as a collection of row vectors.
But making them anything else messes with the nice symetry between:
`a->b->Real` and `N=>M=>Real`, and between currying and slicing.

Multiple-dispatch is *really* strong in for structured matrixes.
Because you need extensibility that requires knowing 2+ types.
And we know that new structured matrixes are constantly being created and its beyond any one library to actually contain them all.
It really surprised me how keen PDE folk are on their Banded Block Banded Matrixes.
I finally wrote up some of my thoughts on this and a few other things re-composability,
https://white.ucc.asn.au/2020/02/09/whycompositionaljulia.html

I think its important to find a solution for structured matrixes that is at least as easy to extend as multiple dispatch.
Haskell-style type-classes may be an answer, one worry i have their is that if people are not using them constantly they will not leap to them as the natural solution.

I have no idea what the XLA story for structured sparse matrixes is.

**Comment by oxinabox** [comment]
#100  does TrianglarMatrixes

**Comment by gilbo** [comment]
@oxinabox just a heads up that this has been one of the main focuses of the adjacent ATL project (that @dougalm is also involved in).  We have a (janky) code prototype I've been working on intermittently here https://github.com/gilbo/atl

And there's an initial publication here: (subject is AD, but you can get a sketch of the indicator-function/predicate idea for treating structure)
https://arxiv.org/abs/2008.11256
