### ISSUE TITLE
static HTML for tutorial is full of red-error messages

### ISSUE THREAD

**Issue by oxinabox** [google-research/dex-lang#534]
see: https://google-research.github.io/dex-lang/examples/tutorial.html

I am not sure if it is out dated (Is it not in the quine tests?)

or if something is going wrong with the run to generate HTML

**Comment by soumith** [comment]
want to just bump this, also read through the tutorial today and saw this.
Especially, starting from this section.
https://google-research.github.io/dex-lang/examples/tutorial.html#s-4

**Comment by apaszke** [comment]
Good point, this is fixed in #688!

**Comment by apaszke** [comment]
And the fix should already be reflected on GitHub pages.
