### ISSUE TITLE
Feature Question: Traversal for Record

### ISSUE THREAD

**Issue by junjihashimoto** [google-research/dex-lang#537]
lens of dex is iso like `#foo` .
https://google-research.github.io/dex-lang/prelude.html#s-42

When define RGB as follows, how do we describe the lens to get `Fin 3 => Fin 8 => Float32` of `#r` axis from `Fin 3 => Fin 8 => RGB Float32`?

```
data RGB n:Type = MkRGB { r: n & g : n & b : n }
```

Is it possible to use `overField` to add `+1` to the `#r` element?
Does dex have traversal of lens?

**Comment by junjihashimoto** [comment]
In this case, I may have to define `Iso (in 3 => Fin 8 => RGB Float32) (RGB  (Fin 3 => Fin 8 => Float32))`.

**Comment by junjihashimoto** [comment]
Is it better to use `map (map (getAt #r))` without considering the troublesome things such as the cost of loop?

**Comment by apaszke** [comment]
Well, you will not escape loops if you want to map an array, but the whole point of Dex is to allow you to write out the loops without having to worry that they're going to be inefficient! So if `map (map (getAt #r))` type-checks, then it's likely what you want.
