### ISSUE TITLE
matshow generating empty base64 PNG data on Mac

### ISSUE THREAD

**Issue by harryaskham** [google-research/dex-lang#548]
`dex repl` after `make install` on `main@HEAD`:

```
>=> import plot

>=> :p matshow $ (for i. for j. 255.0):(Fin 50=>Fin 50=>Float)
(AsList 52 "<img class="plot-img" src="data:image/png;base64, ">")
```

`libpng` is at 1.6.37 via brew.

**Comment by harryaskham** [comment]
Maybe a more instructive example narrowing things down to the `makePNG` call inside `imgToPng`:

```
>=>import png

>=> imgToPng $ (for i j k. 255.0):(Fin 50=>Fin 50=>Fin 3=>Float)
(AsList 0 "")
```

**Comment by apaszke** [comment]
Yeah sorry for that. I just sent a commit that fixes it yesterday, so a pulldown should help!
