### ISSUE TITLE
More flexible typing for table literals 

### ISSUE THREAD

**Issue by srush** [google-research/dex-lang#563]
I generally find it quite clunky to build table literals for non-`Fin` indexing. 

It would be nice if this  worked:

```haskell
for i:YesNo. [0.0, 1.0].i
Type error:
Expected: (Fin 2)
  Actual: {no: Unit | yes: Unit}

for i:YesNo. [0.0, 1.0].i
```
It can be a bit clunky to create these in a named fashion. 

```haskell
for i. case i of 
   {| ... |} -> 0.0 
   {| ... |} -> 1.0
```
Finally, I'm not sure the best way to create tuple indexed tables as casing doesn't work (?) with Fin.

```haskell
for i : (Fin 2 & Fin 2) . case i of 
   ??  -> 0.0 
   ??  -> 1.0
```

**Comment by axch** [comment]
As a workaround, I assume it should be possible to iterate over the desired index set but cast the index to `Fin n`, like so:
```
for i:Bool. [0.0, 1.0].(from_ordinal _ $ ordinal i)
```

But, I concur that a clean type annotation would be nicer if that worked.

**Comment by apaszke** [comment]
FWIW this used to be possible at some point, _right before_ we made `safer-names-dev` the main branch, but we've regressed that capability. In any case, the good news is that we know this can be made to work if we put in the effort.
