### ISSUE TITLE
Bug when unpacking strings

### ISSUE THREAD

**Issue by srush** [google-research/dex-lang#598]
I feel like I should be able to do this right?

```haskell
(AsList _ ls) = "hello"
```

Compiler bug!
Please report this at github.com/google-research/dex-lang/issues

Lookup failed: tmp1:Int32
Checking:
v:Word8 = %ilt tmp1 0
Checking:
def entryFun EntryFun CUDANotRequired []
  v:Word8 = %ilt tmp1 0
  v1:Int32 = %select v 0 tmp1
  v2:(Ptr (CPU, Int32)) = alloc Int32[1]
  v3:(Ptr (CPU, Word8)) = alloc Word8[v1]
  v4:(Ptr (stack, Word8)) = alloc Word8[5]
  store v4 'h'
  v5:(Ptr (stack, Word8)) = v4 +> 1
  store v5 'e'
  v6:(Ptr (stack, Word8)) = v4 +> 2
  store v6 'l'
  v7:(Ptr (stack, Word8)) = v4 +> 3
  store v7 'l'
  v8:(Ptr (stack, Word8)) = v4 +> 4
  store v8 'o'
  store v2 5
  for i:Int32 < 5
      v9:(Ptr (CPU, Word8)) = v3 +> i
      v10:(Ptr (stack, Word8)) = v4 +> i
      v11:Word8 = load v10
      store v9 v11
  v12:Int32 = load v2
  return [v1, v3, v12]

**Comment by dougalm** [comment]
Seems to be fixed since #768 (if not earlier).
