### ISSUE TITLE
Modify data structure in-place with state effect

### ISSUE THREAD

**Issue by chenzizhao** [google-research/dex-lang#602]
Say I'd like to modify the first element of `(AsList 3 [1,2,3])` in place, the effect and reference tools in the prelude don't seem to allow it currently.

Context: incrementally build a tree

**Comment by srush** [comment]
What would inplace modification mean in a functional language? Wouldn't a functional tree just rebuild it with the modified branch.

**Comment by chenzizhao** [comment]
> What would inplace modification mean in a functional language? Wouldn't a functional tree just rebuild it with the modified branch. 

    Ah right I was thinking in the wrong mindset! Thank you for spelling the obvious solution.

**Comment by axch** [comment]
Dex's memory model indeed does not allow provably safe primitives out of which in-place mutation on lists could be composed.  That said, we now have a stack data structure implemented in the Prelude (using `unsafe_coerce` to get at the underlying buffer), so it actually should be possible to write in-place list assignment.  In fact, maybe `stack_push` would be a little cleaner if re-written in terms of it!
