### ISSUE TITLE
GPU and Multicore backends not working

### ISSUE THREAD

**Issue by ted-kord** [google-research/dex-lang#651]
I get a `segmentation core dumped` when I tried the llvm-mc multicore backend on some of the examples: sierpinski, ode_integrator and nn. 

With the GPU backend (llvm-cuda), I get the following: `option --backend: Bad option. Expected one of: ["llvm","llvm-mc","mlir","interpreter"]`.

I have the cuda sdk/toolkit installed and it was picked up when installing Dex.

**Comment by ted-kord** [comment]
I have re-installed Dex again a few times all with the same result. The cuda backend is not recognized.
`option --backend: Bad option. Expected one of: ["llvm","llvm-mc","mlir","interpreter"]`.

I am running the sample script like this: `dex script sierpinski.dx --backend llvm-cuda` .
`

**Comment by tjpalmer** [comment]
I also get the same result when running with `--backend llvm-cuda`. Some build and install log lines include:

```
STEP 11: RUN cd dex-lang && make
clang++-9 -fPIC -I/usr/local/cuda/include -DDEX_CUDA -std=c++11 -fno-exceptions -fno-rtti -DDEX_LIVE -c -emit-llvm src/lib/dexrt.cpp -o src/lib/dexrt.bc
stack build --flag dex:cuda
...
[ 1 of 50] Compiling CUDA
...
STEP 13: RUN cd dex-lang && make install
stack install  --flag dex:optimized --flag dex:cuda
```

Also, `nvidia-smi` works in the podman container I'm running inside of.

**Comment by apaszke** [comment]
#663 should fix the CUDA issues.

**Comment by tjpalmer** [comment]
> #663 should fix the CUDA issues. I'll look into the multicore backend later, but it is even less polished than the CUDA one at this point.

I tried this branch. It doesn't reject the llvm-cuda backend outright, but it also doesn't seem to work for me:

```
$ dex --backend llvm-cuda repl
>=> Small = Fin 5

>=> x = linspace Small (-1.0) 1.5
CUDA driver error at cuDeviceGet (CUDA_ERROR_NOT_INITIALIZED): initialization error
Aborted (core dumped)
$ dex repl
>=> Small = Fin 5

>=> x = linspace Small (-1.0) 1.5

>=> x
[-1., -0.5, 0., 0.5, 1.]
>=> 
```

When running [my full script](https://github.com/contextfreecode/fundiff/blob/7c3560ba7f904c76218904b46eb98321c32aceca/tom/basic.dx), I also get this output:

```
$ dex --backend llvm-cuda script --outfmt result-only basic.dx 
dex: Not a cons list: (((Fin 5) => Float32))
CallStack (from HasCallStack):
  error, called at src/lib/Builder.hs:443:8 in dex-0.1.0.0-EDxLzvE2iIKBpgSlPTyhod:Builder
  unpackRightLeaningConsList, called at src/lib/Parallelize.hs:221:18 in dex-0.1.0.0-EDxLzvE2iIKBpgSlPTyhod:Parallelize
```

**Comment by tjpalmer** [comment]
Of course, those are 1-2 separate issues from the original report. Just figured I'd mentioned the status. I'm not sure how they fit in the grand scheme of things, but if you want me to write up separate issues, let me know.

**Comment by dougalm** [comment]
Closing as obsolete
