### ISSUE TITLE
Automatically gather interface constraints from types

### ISSUE THREAD

**Issue by apaszke** [google-research/dex-lang#668]
The type of a function should spell out the relevant constraints that limit its usage to a set of valid call sites. Argument types are an obvious one, but the required interfaces are another. For example, matrix multiplication cannot be given a type of
```
n=>k=>a -> k=>m=>a -> n=>m=>a
```
because we also require `a` to be a semiring! In Dex we usually denote this by adding a `[Semiring a]` constraint in the definition, which allows us to use the semiring operations in the body. _But_, there are some constraints that we're leaving unsaid! In particular, at the moment we never verify that `n`, `k` and `m` are index sets and if you instantiate the function at something that's not an index set, you're going to get a compiler crash!

So, one thing we could do, is require explicitly spelling out the `[Ix n, Ix k, Ix m]` constraint along the semiring requirement. But, I think there are two issue with that. Firstly, and more importantly, arrays are the fundamental data type in Dex, and if we require someone to understand the type class system then we're seriously increasing the barrier of entry. Think about how you'd explain that in a tutorial! Secondly, it's starting to get verbose. It's not the end of the world, but I would really like Dex to feel like a helpful scripting language, but those requirements force you to fight with the compiler. After all, it's obvious that those types have to be index sets! They appear on the left side of a table arrow!

Let's back track to the beginning of this issue:
> The type of a function should spell out the relevant constraints that limit its usage to a set of valid call sites.

Adding the `Ix` constraints would duplicate the requirements that are already spelled out by the `=>` arrow. So, perhaps instead of requiring the full set of constraints to always be specified explicitly, we could gather the interfaces required _by the types_ and bind them implicitly?

I think it's doable once we start treating our interfaces as globally unique (see #666). And in my opinion it's a very neat solution: it works around both of the issues mentioned above, but it also doesn't forbid you from adding those constraints explicitly if you feel like it.

**Comment by dougalm** [comment]
This was fixed a while ago!
