### ISSUE TITLE
Installation instruction to run dex in other folders?

### ISSUE THREAD

**Issue by el-hult** [google-research/dex-lang#685]
Hi!

I have cloned the repository, installed all dependencies, and installed dex via `make install`. I have created the alias 
```
alias dex=stack exec dex -- --lib-path lib
```
and can run code such as `dex web examples/pi.dx` succesfully, from the folder `/full/path/to/dex-lang`

However, if trying to run in another folder, this fails due to broken paths. I wish to understand if this is a problem on my side, or if there is need to update the installation instructions to make this simpler.

--------------

Two paths in specific, by what I have noticed.

### `lib`
The path to the library is off. Since it is set to the relative path `lib`, I can fix that by using the alias to be 
```
alias dex=stack exec dex -- --lib-path /full/path/to/dex-lang/lib
```

after this, all library files are found.

### `static`
The static-folder `/full/path/to/dex-lang/static` is needed for `dex web` to work. This folder seems to be used here: 
https://github.com/google-research/dex-lang/blob/c47097c9b777cc18039d8798c44301c1e1568789/src/lib/LiveOutput.hs#L169-L171

I cannot pass command line arguments to fix this, so I am currently creating a symlink from my project directory to `/full/path/to/dex-lang/static`. It works. But it is not elegant. Is there some better solution, should the installation instructions be updated, or should this call for a feature request and possible PR? I'm not that well versed in resource packaging in stack projects, but I could investigate it.

----------------------------

With the two fixes above, `dex web` works for me. So it seems not too complicated to fix.

**Comment by el-hult** [comment]
okay... I realize the solution is more less already there, if one reuses the code in `Resources.hs` and `RenderHtml.hs`. 

Is there already someone on this, making my question obsolete soon, or would you like support on this?

**Comment by apaszke** [comment]
Some time ago I've made it so that `make install` would create a self-contained installation of Dex and I think it should still keep working. The web files might have slipped since then, but #686 should fix it.

The alias you've mentioned in this issue is purely meant to be used for compiler development and rapid prototyping. We already seem to be pointing to `make install` in the README, but do let us know if that was confusing.

**Comment by el-hult** [comment]
ok cool. works like a charm now after pulling and reinstalling! nice! :)

I was under the impression that the libs was not available unless you had the `--lib-path` specified, therefore, I used an alias to set that path (actually pointing `~/.local/bin/dex` rather than `stack exec dex`). Now I realize this is not needed. Much simpler!

... and the static folder is now correctly installed. super!
