### ISSUE TITLE
Satisfied constraints don't propagate across datatype definitions

### ISSUE THREAD

**Issue by duvenaud** [google-research/dex-lang#735]
On `safe-names-dev`.  Here's a MWE:

```
data Set a [Ord a] =
  AsSet n:Int elements:(Fin n => a)

data SetIx a l:(Set a) [Ord a] =
  MkSetIx Int
```
gives
```
Type error:Couldn't synthesize a class dictionary for: (Ord a)

data SetIx a l:(Set a) [Ord a] =
                ^^^^^
```

This isn't a blocking issue.

**Comment by axch** [comment]
This can now be worked around by just writing the constraint first, as
```
data SetIx a [Ord a] l:(Set a) =
```
(for example, in the `Element` type in the current `set` library), so I'm going to close this issue as "resolved".
