### ISSUE TITLE
Can't `make` on Mac OS Catalina 10.15.7

### ISSUE THREAD

**Issue by git-yledu** [google-research/dex-lang#738]
Hi, Followed all instructions, makes gives me

```
stack --stack-yaml=stack-macos.yaml build
dyld: malformed mach-o: load commands size (34520) > 32768
make: *** [build] Abort trap: 6
```

so I still have to use Matlab, plz help me !

**Comment by apaszke** [comment]
Hmmm looks like it's a recurring issue with Stack and I'm not sure how much we can do to help with that. There are some hints [in this SO thread](https://stackoverflow.com/questions/39646221/stack-gives-dyld-malformed-mach-o). Hope those help 😕

**Comment by git-yledu** [comment]
I did `brew remove haskell-stack` then `brew reinstall haskell-stack` as advised, and it seems to work now. Also added `export PATH="/usr/local/opt/llvm@9/bin:$PATH"`

Dunno really what did it. But thanks !

**Comment by apaszke** [comment]
No clue why that helps, but I'm glad it works now! 🤷
