### ISSUE TITLE
Compiler error with a message to please report

### ISSUE THREAD

**Issue by emilyfertig** [google-research/dex-lang#754]
When I run either `dex repl` or `dex script examples/...` I get the following:

```
Compiling the prelude. This may take some time.
Compiler bug!
Please report this at github.com/google-research/dex-lang/issues

unhandled function attribute enum value: FunctionAttributeKind 66
CallStack (from HasCallStack):
  error, called at src/LLVM/Internal/Attribute.hs:222:17 in llvm-hs-12.0.0-7NymWkhn5XUHr6ULqIaFTn:LLVM.Internal.Attribute
  decodeM, called at src/LLVM/Internal/Coding.hs:77:10 in llvm-hs-12.0.0-7NymWkhn5XUHr6ULqIaFTn:LLVM.Internal.Coding
  decodeM, called at src/LLVM/Internal/Attribute.hs:248:5 in llvm-hs-12.0.0-7NymWkhn5XUHr6ULqIaFTn:LLVM.Internal.Attribute
  decodeM, called at src/LLVM/Internal/Module.hs:555:61 in llvm-hs-12.0.0-7NymWkhn5XUHr6ULqIaFTn:LLVM.Internal.Module
```

I followed the installation instructions on the front page, except using LLVM and Clang 12 instead of 9, and `safe-names-dev` instead of `main` (following @sharadmv 's advice, as a workaround for other issues). This is on gLinux, at commit fd33285.

**Comment by apaszke** [comment]
That's quite surprising. We've updated to LLVM 12 just yesterday, so it's not a very well trodden path, but we haven't seen this one just yet. I'll try to reproduce and fix it tomorrow!

**Comment by apaszke** [comment]
Oh, I think it's because we might still be using older versions of clang! Could you try installing clang++-9 and rebuilding?

**Comment by emilyfertig** [comment]
That fixed it, thanks!
