### ISSUE TITLE
Naming convention in the standard library and examples

### ISSUE THREAD

**Issue by axch** [google-research/dex-lang#786]
Status quo is `camelCase`.  How about moving to `snake_case` for functions and variables (but leaving types and constructors `camelCase`)?  It seems less annoying, and more congruent with Python and Julia.

**Comment by tscholak** [comment]
No preference except for consistency. Is the casing currently enforced by the parser?

**Comment by apaszke** [comment]
It used to be, but now it shouldn't. That doesn't mean that I guarantee we don't do this, but if we do, then it's a bug!

I'm also in favor of changing the conventions. What about type names though? Do you want to do `camelCase` or `CapitalCamelCase` as we used to do (and Python does as well)?

**Comment by axch** [comment]
I assume `CapitalCamelCase` is the status quo for type names?  I'll leave it as-is.

**Comment by axch** [comment]
On starting to do this, a question arises: When a function refers to a type or a constructor in its name, is it nicer to `snake_case` the type name as well, or keep the reference `CapCamelCase` so it's identical with the type?  If the latter, should we have the underscore in front of it?  Some examples to stimulate discussion:
- `i64_to_raw_ptr`, `i64_to_RawPtr`, or `I64_to_RawPtr`?  Or `Int64_to_RawPtr`?
- `is_just`, `is_Just`, or `isJust`?
- `yield_state`, `yield_State`, or `yieldState`?
- `from_integer`, `from_Integer`, or `fromInteger`?
- `unsafe_io`, `unsafe_IO`, or `unsafeIO`?
- `cast_ptr`, `cast_Ptr`, or `castPtr`?
- `tab_from_ptr`, `tab_from_Ptr`, or `tab_fromPtr`?  (Status quo is `tabFromPtr`)
- `to_list`, `to_List`, or `toList`?
- `swap_either_iso`, `swap_Either_Iso`, or `swapEitherIso`?
