### ISSUE TITLE
We should not be catching ThreadKilled

### ISSUE THREAD

**Issue by axch** [google-research/dex-lang#801]
Context: I'm trying to run a Dex evaluation in a Haskell worker thread, and to (sometimes) abort that thread with `killThread`.

Symptom: When I kill the worker, it doesn't actually die, but instead "completes" with the result
```
Compiler bug!
Please report this at github.com/google-research/dex-lang/issues

thread killed
```
This is a violation of the semantics of `killThread`.

Expected behavior: The worker thread should die, not recover.

Workaround: As it happens, I already have code that handles the case of my not killing the worker fast enough, which coincidentally also handles the case of the worker completing with "I was killed" instead of actually dying; but this situation is a horrible threading bug waiting to happen.

Presumed cause: The `SomeException` handler in https://github.com/google-research/dex-lang/blob/main/src/lib/Err.hs#L245.

Deeper cause: Haskell's default exception ecosystem being broken (why is it so hard to `catch` just the non-asynchronous exceptions?).  There are opinions on best practices to adopt to avoid getting bitten like this; do we want to adopt any of them?
- https://www.fpcomplete.com/haskell/tutorial/exceptions/
- https://www.tweag.io/blog/2020-04-16-exceptions-in-haskell/

**Comment by apaszke** [comment]
Would it be sufficient to special case `ThreadKilled` in `catchIOExcept`? We definitely want to have a catch all so that a surprising programming error in one source block doesn't trip up the whole compiler/live evaluator process.
