### ISSUE TITLE
grad at record infloops the compiler

### ISSUE THREAD

**Issue by axch** [google-research/dex-lang#818]
The following lovely snippet
```
def MyPair : Type = { foo: Float & bar: Float}

grad (\p. get_at p #foo + get_at p #bar) (1, 2)
```
causes Dex to enter an apparently infinite loop, consuming all available RAM until killed.  When I limited Dex's RAM to 1G (or 2G), it ran with no output for at least ~3 minutes before I got bored and killed it.

Expected behavior: a type error saying that `MyPair` and `(Float, Float)` are not the same type, or else an implicit isomorphism from one to the other.

For reference, here is the output of `--logto` on this example:
```
[ MyPair:Type = {foo: Float & bar: Float}]
[=== rename ===]
[Starting rename]
[ === Result ===
(Abs  MyPair:Type =
       {foo: Float
       & bar: Float} MyPair @> [Atom name: MyPair defined in main]
) ]
[=== typed ===]
[Starting typed]
[=== Result ===  {bar: Float32 & foo: Float32}]
[Running checks]
[Checks passed]
[=== synth ===]
[Starting synth]
[=== Result ===  {bar: Float32 & foo: Float32}]
[Running checks]
[Checks passed]
[=== simp ===]
[Starting simp]
[=== Result ===  () Reconstruction abs: (Abs  {bar: Float32 & foo: Float32})]
[Running checks]
[Checks passed]
[ === Top name ===
MyPair =
Atom name: Decl
  type:  Type
  value: {bar: Float32 & foo: Float32}

===
 ]
[ (grad
   (\p. (+)
          (get_at p
             (MkIso
                {fwd=(\{foo=x, ...r}. (,) x r)
                , bwd=(\(x, r). {foo=x
                         , ...r})}))
          (get_at p
             (MkIso
                {fwd=(\{bar=x, ...r}. (,) x r)
                , bwd=(\(x, r). {bar=x
                         , ...r})}))) ((,) 1 2)) ]
[=== rename ===]
[Starting rename]
[ === Result ===
(grad
   (\p. (+)
          (get_at p
             (MkIso
                {fwd=(\{foo=x, ...r}. (,) x r)
                , bwd=(\(x, r). {foo=x
                         , ...r})}))
          (get_at p
             (MkIso
                {fwd=(\{bar=x, ...r}. (,) x r)
                , bwd=(\(x, r). {bar=x
                         , ...r})}))) ((,) 1 2)) ]
[=== typed ===]
[Starting typed]
```

**Comment by axch** [comment]
Update: This is actually very poor Dex usage, because `get_at` is supposed to take the isomorpism first, and because `{ : & : }` is syntax for record _types_, whereas record _objects_ are supposed to be spelled `{ = , = }` (why are these different?).  However, it does tickle an infinite loop in the unifier, and obvious shrinkings do not.

The bug is this: when trying to unify `{ foo: ?a & ...?c }` with `{ bar: ?b & ...?c }` (i.e., two record types with different fields but the same tail variable), the unifier allocates a fresh `?d` and adds the equations
- `?c = { bar: ?b & ...?d }`
- `?c = { foo: ?a & ...?d }`
in that order.  After zonking `?c`, the second equation turns into `{ bar: ?b & ...?d } = { foo: ?a & ...?d }`, and the cycle repeats.  Instead, the unifier should figure out that the original record must have both `foo` and `bar` fields.

**Comment by apaszke** [comment]
This doesn't sound right to me. I don't think there's a single value for `c` that would make those two types unify so we should straight up reject this as a type error

**Comment by axch** [comment]
Why not?  `?c = {foo: ?a & bar: ?b & ...?d}` looks to me like the most general solution to those two equations (given that `&` is unordered).

**Comment by apaszke** [comment]
As discussed outside of this issue tracker, this substitution wouldn't work. Dex records do support repeated fields and the proposed solution would still have the type differ by the multiplicity `foo` and `bar` appear in respective record types.
