### ISSUE TITLE
Machine learning library in Idris

### ISSUE THREAD

**Issue by joelberkeley** [google-research/dex-lang#823]
Hi Dex team,

Apologies if this isn't the place to mention this, but I've just been pointed towards your project, and I thought I should mention a machine learning library I've been writing for the last year in Idris. It's here

https://github.com/joelberkeley/spidr

I should mention the README _Motivation_ might have changed a bit since I wrote it. It's looking at purely functional machine learning with dependent types, but uses XLA. It doesn't have autodiff or accelerator support yet (they're next). It approaches the Tensor design fairly differently to Dex, and I'm interested to learn more about your approach.

Do you have any public forums I can join to follow your work?

Thanks,
Joel

**Comment by axch** [comment]
Thanks for reaching out!  It's always exciting to see more people investing in strong typing for ML.  This may be a bit off topic, but I personally have always wanted to see someone use a really good dependent type system to prove correctness of some probabilistic programming-type programs or libraries, for instance a correct-by-construction MCMC algorithm.

As to the concrete question about a public forum, Github is where the action is.  Check out the discussions section, in particular.

(Closing as this isn't really an "issue", per se.)
