### ISSUE TITLE
Define policy for %time and %bench in examples

### ISSUE THREAD

**Issue by axch** [google-research/dex-lang#910]
It seems useful to include `%time` and `%bench` commands in committed Dex examples, both to show users those commands exist, and to show how fast (or slow) Dex is.

However, and example like that cannot be added to the `check-quine` test suite, because the latter will never see the same timing as when the example was committed, and thus will always fail.

What should we do?
- Avoid automatically checking such examples?
- Add a --conceal-timings=False flag to Dex to make quine tests ignore timings?
- Define some clever scheme to parse saved timing information and use it to prevent performance regressions?  (Though, need to be robust to different CPUs and loading levels.)

Speaking of which, do we trust the automatic example compilation Action to provide decent resources for timings?

**Comment by dougalm** [comment]
Another option might be to make the quine tests check that the programs are merely quines "modulo timing results" by filtering out lines that contain timing info before checking the output against the expected result. We just need some way of detecting the timing lines and it doesn't need to be perfect.

**Comment by apaszke** [comment]
Yeah, a quick sed might be good enough!

**Comment by apaszke** [comment]
But also I don't see much value in adding too many of those snippets in examples. They're nice for debugging, but not sure about checking them in?
