### ISSUE TITLE
Consider separating binders in instance definitions

### ISSUE THREAD

**Issue by axch** [google-research/dex-lang#926]
Status quo for defining an instance looks like this:
```
instance {n} {i:n} [Ix n] Ix (..i)
  ...
```
Can you tell what's going on here?

The proposal is to syntactically separate the binders from the class, for example
```
instance Ix (..i) given {n} {i:n} [Ix n] 
  ...
```
or
```
instance Ix (..i) for {n} {i:n} [Ix n] 
  ...
```
to make it move obvious what class is getting a new instance, and at what type, and move the conditions to a secondary position.

Opinions?  Discuss!

**Comment by axch** [comment]
Based on offline discussion with @dougalm, the plan of record is to yes implement this, with `given` as the separator keyword.  If we like it, we could also consider permitting `given` in `def`, for the same purpose.

**Comment by apaszke** [comment]
`given` SGTM! I agree the current syntax is quite unreadable.

**Comment by duvenaud** [comment]
I also like this change, it matches the order I have to think about things when writing a signature.  It will also make it easier to search for instances.
