### ISSUE TITLE
Compiler bug when implementing `Ix`

### ISSUE THREAD

**Issue by midfield** [google-research/dex-lang#930]
```
data T =
  A
  B

all_t = [A, B]

instance Ix T
  size = 2
  ordinal = \t. case t of
    A -> 0
    B -> 1
  --unsafe_from_ordinal = \o. if o == 0 then A else B
  unsafe_from_ordinal = \o. all_t.(o @ _)

test : (T => Nat) = [0, 1]
```

results in:

```
Compiler bug!
Please report this at github.com/google-research/dex-lang/issues

shouldn't happen?
CallStack (from HasCallStack):
  error, called at src/lib/JIT.hs:1032:17 in dex-0.1.0.0-6YSqRVo9AYNCATbpRfLD0m:JIT
```

Note if you replace switch the `unsafe_from_ordinal` definitions the bug goes away.  I've tried various other options, basically anything that references `all_t` is problematic.  This is as small as I was able to make the reproducible bug.

The context is, I am writing a PCFG parser for a small grammar and was using a sum type (and sums of sum types) for the grammar.  To convert between numeric and symbolic forms I wanted to use `Ix` as a kind of type-level lookup table.  It is laborious to write these out by hand without something like `deriving Enum` so I was hoping to use something like `all_t` as a labor-saving device.  @axch pointed me at @duvenaud's "sets of string" thing so I may try that next.

**Comment by axch** [comment]
On a technical level the issue seems to be that `TopLevel.abstractPtrLiterals` (called from `Toplevel.evalLLVM`) doesn't notice the reference to `all_t` that's embedded in the `Ix` instance for `T`.  @dougalm @apaszke any thoughts on what to do about that?

**Comment by apaszke** [comment]
I tried to take multiple stabs at solving this, but I can't find a reasonably hacky way to make this work. The proper fix is to move the simplification of different indices to natural numbers earlier into our lowering pipeline, before we ever get to Imp. It's one of the next things I'll want to do, but it will take more time 😕
