### ISSUE TITLE
The syntax of ":" is super-confusing

### ISSUE THREAD

**Issue by axch** [google-research/dex-lang#933]
What might a line like
```
foo : (Fin 3) => Float
```
mean, in Dex syntax?

To the uneducated eye, it might seem that this is a straightforward case of referencing the variable `foo`, with type annotation `(Fin 3) => Float`.  Indeed, that was the effect I was trying to achieve, for I had defined `foo` as `ones`, a function of type `a:Type ?-> Ix a ?=> a => Float` with all arguments implicit; I was trying to supply them with the type annotation.

Imagine my confused frustration when the above refused to parse.

Trying to understand what was happening, I source-dove the expression parser, and discovered an alternative: Perhaps this is being interpreted as a pi type, namely the array type `(Fin 3) => Float`, where I named the elements of the `(Fin 3)` as `foo` but neglected to reference them?  I tried to forestall that possibility by writing
```
foo : ((Fin 3) => Float)
```
but that did not have the desired effect either.  Nor, in retrospect, could it have had the desired effect, because the parser for pi types commits when it sees a complete annotated binder, without waiting for an arrow.  (Why?)

Further flailing at length brought me to the parser for _decls_, which it took me a long time to think of because I was very strongly primed that I was authoring an expression, whereupon I discovered that _it_ commits to a type-annotated let binding when it sees the `:`, without waiting for the `=` that one would think would be dispositive.

In retrospect, it is possible to forestall that interpretation by wrapping my putative expression in parens, thus:
```
(foo : (Fin 3) => Float)
```

whereupon it does successfully parse --- as a pi type.  In the event, I temporarily modified the decl parser to not commit until the `=`.  But that's still not the parse I want!  What can I do to prevent the pi type interpretation?

After a great deal of additional flailing, I finally thought to check the parser for the thing I was trying to create, namely a variable occurrence.  Surely a string of letters outside a pattern-match context that does not form a keyword is a variable occurrence?  No!  A string of letters outside a pattern match context that does not form a keyword is a variable occurrence _unless followed by a `:`_, because that's how pi type binders are disambiguated!  So in the end, I am able to achieve the desired effect by hiding from the colon on both sides:
```
((foo) : (Fin 3) => Float)
```

Because `(foo)` is definitely an expression (which can be type-annotated), but just `foo` stops being an expression and becomes a pi type binder as soon as you try to type-annotate it.  With any type, even one that cannot be a pi because it doesn't expose any arrows.

Perhaps we should remove the special case that lets `:` retroactively make a name not be a variable, and accept a parser performance regression by making decl commit on `=` and pi commit on arrow?  Or maybe change the syntax of either "type-annotate a binder" or "type-annotate an expression" so they are not the same?  Otherwise we will have to teach this to users over and over: "`:` is the type annotation operator, except if the LHS is a name, in which case the whole thing is a type-annotated binder, whether there is any context that can consume that binder or not."

**Comment by axch** [comment]
On second thought, that change to the parser doesn't work, because then the "variable occurrence" parse commits too eagerly, and it becomes impossible to write `a:Type ?-> (Ix a) ?=> a=>Float`.  Perhaps the cleanest solution would be say that `:` (single colon) is always a type-annotated binder, and type-annotating an expression is spelled `::` (double colon)?

**Comment by dougalm** [comment]
Totally agree that `:` is extremely confusing. I like the idea of syntactically distinguishing binder/pattern annotation from occurrence/expression annotation, using `:` for one and `::` for the other. We can even imagine going as far as making `::` an ordinary prelude-define infix operator, `(::) : (a:Type) -> a -> a`. Unfortunately, we want the arguments in the other order.

Related, we have a confusing mix of rules around parentheses and annotated binders. Do they go around the binder/type pair, like `(x : List a)`, or just the type, like `x : (List a)` ?

**Comment by apaszke** [comment]
I agree that we should force parens around dependent pi binders. To make matters worse, I think that we even might _not accept_ the parenthesized version in the parser...
