### ISSUE TITLE
Compiler Bug! :html x

### ISSUE THREAD

**Issue by pharringtonp19** [google-research/dex-lang#934]
The final output of the code asked me to report this as a bug (Although, I wouldn't be surprised if I was making a mistake somewhere).

running `dex web script_name.dx` where script_name contains the following code

```
Height = Fin 3 
Width = Fin 8

x = for i:Height. for j:Width. 1.0
x
```
produces the following error 
```
Parse error:5:2:
  |
5 | x
  |  ^
unexpected end of input
expecting "..", "..<", "<..", "<..<", "=>", '$', ''', '.', ':', '@', '_', alphanumeric character, arrow, backquoted name, end of line, expression, infix operator, or let binding
```
taking a guess as to how to correct this, I tried  the following
```
Height = Fin 3 
Width = Fin 8

x = for i:Height. for j:Width. 1.0
:html x 
```
which produces the following: 
```
Compiler bug!
Please report this at github.com/google-research/dex-lang/issues

Not a string: (view i:(Fin 3) . 
 view i1:(Fin 8) . 
  v:Int32 = %cast Int32 i
  v1:Int32 = %cast Int32 i1
  v2:Int32 = %imul v 8
  v3:Int32 = %iadd v1 v2
  v4:(Ptr (CPU, Float32)) = ptr3 +> v3
  v5:Float32 =
   %runIO
     (\_ign:Unit.
         v5:Float32 = load v4
        v5)
 v5)
CallStack (from HasCallStack):
  error, called at src/lib/Serialize.hs:76:18 in dex-0.1.0.0-6YSqRVo9AYNCATbpRfLD0m:Serialize
```

**Comment by chenzizhao** [comment]
Try adding a new line (to fix the first parser error)?

**Comment by pharringtonp19** [comment]
@chenzizhao perfect! --thanks

**Comment by axch** [comment]
Yeah, files without a trailing newline are unfortunate.  It would be nice to accept those, but if I patch Dex to do that, this happens:
```
$ echo -n "1" > no-eof.dx
$ dex script no-eof.dx
1> 1
```
If the expression has no end-of-line, then no end-of-line is printed when it's echoed, and the `> `-delimited result starts right there, which is pretty confusing.  Though, to be fair, the parse error is pretty confusing too.

That `:html` compiler crash is a bug, though, which we ought to patch.

**Comment by axch** [comment]
Erm, right.  The crash is a bug, but actually writing `:html` there is incorrect: `:html` expects a Dex `String` containing HTML, which it then embeds into the web notebook.  We use this for drawing plots from Dex using SVG.  If you try to use `:html` on a non-`String`, you ought to get a type error telling you not to.
