### ISSUE TITLE
Interface constraints in lambdas

### ISSUE THREAD

**Issue by axch** [google-research/dex-lang#954]
Lambdas permit
- Explicit parameters: `\a. a + 1`
- Implicit parameters: `\{a} (x:a). x`
- But not class constraints:
```
\{n} [Ix n] (xs:n=>Float). sum xs
> Type error:Not a data constructor: Ix
>
> \{n} [Ix n] (xs:n=>Float). sum xs
>       ^^^^
```
The error is due to parsing the attempted constraint as a pattern match for singleton table literal.

Is there any way to spell the desired function anonymously?
```
\{n} (xs:n=>Float). sum xs
> Type error:Couldn't synthesize a class dictionary for: (Ix n)
>
> \{n} (xs:n=>Float). sum xs
>          ^^^^^^^^

\xs. sum xs
> Type error:Ambiguous type variable
>
> \xs. sum xs
>      ^^^^
```

**Comment by apaszke** [comment]
Yeah I think there might be no way to spell it out right now, other than giving a type annotation to the whole lambda expression. In that case, type inference will insert the implicit binders that you haven't spelled out after `\`.
