### ISSUE TITLE
Auto-currying and implicit arguments break custom linearizations

### ISSUE THREAD

**Issue by axch** [google-research/dex-lang#990]
As of PR #989, Dex will allow custom linearizations to apply to polymorphic functions.  However, this exposes an unfortunate interaction with implicit parameters.  Consider an arbitrary definition such as
```
def w {n} [Ix n] (x:n=>Float) : n=>Float = 2 .* x
-- Intentionally give a different derivative from the computed one
def wLin {n} [Ix n] (x:n=>Float) : (n=>Float & n=>Float -> n=>Float) = (w x, \xt:(n=>Float). 4 .* xt)

custom-linearization w wLin
```

The we get the following unintuitive (at least to me) behavior:
```
jvp (\x. w x) [1.0, 1.0] [1.0, 0.0]
> [4., 0.]  -- As expected
```
but
```
jvp w [1.0, 1.0] [1.0, 0.0]
> [2., 0.]  -- !?  Where's my custom linearization?
```

Why did this happen?  Because the single reference to `w` is actually the partial application `(w _ _)` that fills in the implicit arguments; and that partial application is reduced eagerly in compiler, losing its association with the custom linearization (which is attached to the `w` object itself).  The same thing would presumably happen to a partial application of a binary function, even if all the arguments were explicit.

This seems like a severe footgun we should address.

**Comment by dougalm** [comment]
Fixed by #1209.
